title: HEDTools
description: Tools to support event annotation using hierarchical event descriptor (HED) tags.
theme: jekyll-theme-cayman
gems:
   - jekyll-mentions
   - jemoji
   - jekyll-redirect-from
   - jekyll-sitemap
   - jekyll-feed
