function test_suite = test_parsehedstr%#ok<STOUT>
initTestSuite;

function values = setup %#ok<DEFNU>
Maps = load('HEDMaps.mat');
values.hedMaps = Maps.hedMaps;
values.EmptyString = '';
values.HEDString1 = ['Event/Label/Test1,' ...
    'Event/Category/Participant response,' ...
    'Event/Description/This is a test,' ...
    '(Participant ~ ' ...
    'Action/Control vehicle/Drive/Collide ~ ' ...
    'Item/Object/Vehicle/Car)'];
values.HEDString2 = ['Event/Label/Test1,' ...
    'Event/Category/Participant response,' ...
    'Event/Description/This is a test (Participant ~ ' ...
    'Action/Control vehicle/Drive/Collide ~ ' ...
    'Item/Object/Vehicle/Car)'];
values.HEDString3 = ['(Participant ~ ' ...
    'Action/Control vehicle/Drive/Collide ~ ' ...
    'Item/Object/Vehicle/Car),' ...
    'Event/Label/Test1,' ...
    'Event/Category/Participant response,'];

function teardown(values) %#ok<INUSD,DEFNU>
% Function executed after each test

function testCheckGroupBrackets(values)  %#ok<DEFNU>
% Unit test for editmaps
fprintf('\nUnit tests for checkgroupbrackets\n');

fprintf('\nIt should return no errors when there is a empty HED string');
errors = parsehedstr(values.hedMaps, values.EmptyString, false);
assertTrue(isempty(errors));

fprintf('\nIt should return no errors when the HED string is valid');
errors = parsehedstr(values.hedMaps, values.HEDString1, false);
assertTrue(isempty(errors));

fprintf(['\nIt should return errors when there is a missing comma' ...
    ' before a group']);
errors = parsehedstr(values.hedMaps, values.HEDString2, false);
assertFalse(isempty(errors));

fprintf(['\nIt should return errors when there is a required tag' ...
    ' missing']);
errors = parsehedstr(values.hedMaps, values.HEDString3, false);
assertFalse(isempty(errors));