% tagdir_input
% GUI for input needed to create inputs for tagdir function
%
% Usage:
%   >>  tagdir_input()
%
% Description:
% tagcsv_input() brings up a GUI for input needed to create inputs for
% tagdir
%
% Function documentation:
% Execute the following in the MATLAB command window to view the function
% documentation for tagdir_input:
%
%    doc tagdir_input
% See also: tagdir, pop_tagdir
%
% Copyright (C) Kay Robbins and Thomas Rognon, UTSA, 2011-2013,
% krobbins@cs.utsa.edu
%
% This program is free software; you can redistribute it and/or modify
% it under the terms of the GNU General Public License as published by
% the Free Software Foundation; either version 2 of the License, or
% (at your option) any later version.
%
% This program is distributed in the hope that it will be useful,
% but WITHOUT ANY WARRANTY; without even the implied warranty of
% MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
% GNU General Public License for more details.
%
% You should have received a copy of the GNU General Public License
% along with this program; if not, write to the Free Software
% Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
%
% $Log: tagdir_input.m,v $
% $Revision: 1.0 21-Apr-2013 09:25:25 krobbins $
% $Initial version $
%

function [inDir, baseMap, doSubDirs, editXml, preservePrefix, ...
    rewriteOption, saveMapFile, selectOption, useGUI, writeTags, ...
    cancelled] = tagdir_input()

% Setup the variables used by the GUI
baseMap = '';
cancelled = true;
doSubDirs = true;
inDir = '';
preservePrefix = false;
editXml = false;
rewriteCtrl = '';
preservePrefixCtrl = '';
rewriteOption = 'Both';
editXmlCtrl = '';
saveMapFile = '';
selectOption = true;
useGUI = true;
title = 'Inputs for tagging directory of data files';
writeTags = true;
inputFig = figure( ...
    'Color', [.94 .94 .94], ...
    'MenuBar', 'none', ...
    'Name', title, ...
    'NextPlot', 'add', ...
    'NumberTitle','off', ...
    'Resize', 'on', ...
    'Tag', title, ...
    'Toolbar', 'none', ...
    'Visible', 'off', ...
    'WindowStyle', 'modal');
createLayout();
movegui(inputFig); % Make sure it is visible
uiwait(inputFig);

    function createLayout()
        createBrowsePanel();
        createWriteGroupPanel();
        createOptionsGroupPanel();
        createButtonPanel();
    end

    function createBrowsePanel()
        browsePanel = uipanel('BorderType','none', ...
            'BackgroundColor',[.94 .94 .94],...
            'FontSize',12,...
            'Position',[0 .7 1 .3]);
        uicontrol('Parent', browsePanel, ...
            'Style','text', 'String', 'Directory', ...
            'Units','normalized',...
            'HorizontalAlignment', 'Left', ...
            'Position', [0.015 0.8 0.1 0.13]);
        uicontrol('Parent', browsePanel, ...
            'Style','text', 'String', 'Base tags', ...
            'Units','normalized',...
            'HorizontalAlignment', 'Left', ...
            'Position', [0.015 0.5 0.12 0.13]);
        uicontrol('Parent', browsePanel, ...
            'Style','text', 'String', 'Save tags', ...
            'Units','normalized',...
            'HorizontalAlignment', 'Left', ...
            'Position', [0.015 .2 0.12 0.13]);
        dirCtrl = uicontrol('Parent', browsePanel, 'Style', 'edit', ...
            'BackgroundColor', 'w', 'HorizontalAlignment', 'Left', ...
            'Tag', 'DirectoryEdit', 'String', '', ...
            'TooltipString', ...
            'Directory of .set files for visualization', ...
            'Units','normalized',...
            'Callback', {@dirCtrlCallback}, ...
            'Position', [0.15 0.7 0.6 0.25]);
        tagsCtrl = uicontrol('Parent', browsePanel, 'style', 'edit', ...
            'BackgroundColor', 'w', 'HorizontalAlignment', 'Left', ...
            'Tag', 'BaseTagsEdit', 'String', '', ...
            'TooltipString', ...
            'Directory of .set files for visualization', ...
            'Units','normalized',...
            'Callback', {@tagsCtrlCallback}, ...
            'Position', [0.15 0.4 0.6 0.25]);
        saveTagsCtrl = uicontrol('Parent', browsePanel, 'Style', 'edit', ...
            'BackgroundColor', 'w', 'HorizontalAlignment', 'Left', ...
            'Tag', 'SaveTags', 'String', '', ...
            'TooltipString', ...
            'Complete path for saving the consolidated event tags', ...
            'Units','normalized',...
            'Callback', {@saveTagsCtrlCallback}, ...
            'Position', [0.15 0.1 0.6 0.25]);
        uicontrol('Parent', browsePanel, ...
            'string', 'Browse', ...
            'style', 'pushbutton', 'TooltipString', ...
            'Press to bring up directory chooser', ...
            'Units','normalized',...
            'Callback', {@browseDirCallback, dirCtrl, ...
            'Browse for input directory'}, ...
            'Position', [0.775 0.7 0.21 0.25]);
        uicontrol('Parent', browsePanel, ...
            'string', 'Browse', 'style', 'pushbutton', ...
            'TooltipString', 'Press to choose BaseTags file', ...
            'Units','normalized',...
            'Callback', {@browseTagsCallback, tagsCtrl, ...
            'Browse for base tags'}, ...
            'Position', [0.775 0.4 0.21 0.25]);
        uicontrol('Parent', browsePanel, ...
            'string', 'Browse', 'style', 'pushbutton', ...
            'TooltipString', 'Press to find directory to save tags object', ...
            'Units','normalized',...
            'Callback', {@browseSaveTagsCallback, saveTagsCtrl, ...
            'Browse for base tags'}, ...
            'Position', [0.775 0.1 0.21 0.25]);
    end % createBrowsePanel

    function createOptionsGroupPanel()
        % Create the button panel on the side of GUI
        optionGroupPanel = uipanel('BackgroundColor',[.94,.94,.94],...
            'FontSize',12,...
            'Title','Other options', ...
            'Position',[0.535 .2 .45 .5]);
        u1 = uicontrol('Parent', optionGroupPanel, ...
            'Style', 'CheckBox', 'Tag', 'WriteTagsCB', ...
            'String', 'Write tags to dataset', 'Enable', 'on', 'Tooltip', ...
            'Write tags to the .event and .etc fields of the datasets', ...
            'Units','normalized', ...
            'Callback', @writeTagsCallback, ...
            'Position', [0.1 0.85 0.8 0.1]);
        set(u1, 'Value', get(u1, 'Max'));
        u2 = uicontrol('Parent', optionGroupPanel, ...
            'Style', 'CheckBox', 'Tag', 'DoSubDirsCB', ...
            'String', 'Look in subdirectories', 'Enable', 'on', 'Tooltip', ...
            'Traverse all subdirectories to process .set files', ...
            'Units','normalized', ...
            'Callback', @doSubDirsCallback, ...
            'Position', [0.1 0.7 0.8 0.1]);
        set(u2, 'Value', get(u2, 'Max'));
        u3 = uicontrol('Parent', optionGroupPanel, ...
            'Style', 'CheckBox', 'Tag', 'SelectOptionCB', ...
            'String', 'Use GUI to select fields to tag', 'Enable', 'on', 'Tooltip', ...
            'If checked, you will be presented with a GUI to select fields to tag', ...
            'Units','normalized', ...
            'Callback', @selectCallback, ...
            'Position', [0.1 0.55 0.8 0.1]);
        set(u3, 'Value', get(u3, 'Max'));
        u4 = uicontrol('Parent', optionGroupPanel, ...
            'Style', 'CheckBox', 'Tag', 'UseGUICB', ...
            'String', 'Use GUI to edit tags', 'Enable', 'on', 'Tooltip', ...
            'Use cTagger GUI to edit consolidated tags', ...
            'Units','normalized', ...
            'Callback', @useGUICallback, ...
            'Position', [0.1 0.4 0.8 0.1]);
        set(u4, 'Value', get(u4, 'Max'));
        editXmlCtrl = uicontrol('Parent', optionGroupPanel, ...
            'Style', 'CheckBox', 'Tag', 'editXml', ...
            'String', 'XML can be edited', 'Enable', 'on', 'Tooltip', ...
            'cTagger GUI to edit consolidated tags', ...
            'Units','normalized', ...
            'Callback', @editXmlCallback, ...
            'Position', [0.1 0.25 0.8 0.1]);
        set(editXmlCtrl, 'Value', get(editXmlCtrl, 'Min'));
        preservePrefixCtrl = uicontrol('Parent', optionGroupPanel, ...
            'Style', 'CheckBox', 'Tag', 'PreservePrefixfield', ...
            'String', 'Preserve tag prefixes', 'Enable', 'on', 'Tooltip', ...
            'Do not consolidate tags that share prefixes', ...
            'Units','normalized', ...
            'Callback', @preservePrefixCallback, ...
            'Position', [0.1 0.1 0.8 0.1]);
        set(preservePrefixCtrl, 'Value', get(preservePrefixCtrl, 'Min'));
    end % createOptionsGroupPanel

    function createWriteGroupPanel()
        % Create the button panel on the side of GUI
        rewriteGroupPanel = uipanel('BackgroundColor',[.94,.94,.94],...
            'FontSize',12,...
            'Title','Precision and save options', ...
            'Position',[0.015 .2 .45 .5]);
        uicontrol('Parent', rewriteGroupPanel, ...
            'Style', 'RadioButton', 'Tag', 'Summary', ...
            'String', 'Double (.set file)', 'Enable', 'On', ...
            'Tooltip', 'Add tag summary to .etc.tags field of data', ...
            'Units','normalized', ...
            'Callback', @rewriteCallback, ...
            'Position', [0.1 0.8 0.8 0.1]);
        uicontrol('Parent', rewriteGroupPanel, ...
            'Style', 'RadioButton', 'Tag', 'Individual', ...
            'String', 'Single (.set file)', 'Enable', 'on', 'Tooltip', ...
            'Add tags to individual events in .events.usertags', ...
            'Units','normalized', ...
            'Callback', @rewriteCallback, ...
            'Position', [0.1 0.6 0.8 0.1]);
        rewriteCtrl = uicontrol('Parent', rewriteGroupPanel, ...
            'Style', 'RadioButton', 'Tag', 'Both', ...
            'String', 'Single (.set and .fdt)', 'Enable', 'on', 'Tooltip', ...
            ['Rewrites tag summary to .etc.tags and tags to ' ...
            'individual events through .event.usertags'], ...
            'Units','normalized', ...
            'Callback', @rewriteCallback, ...
            'Position', [0.1 0.4 0.8 0.1]);
        set(rewriteCtrl, 'Value', get(rewriteCtrl, 'Max'));
        uicontrol('Parent', rewriteGroupPanel, ...
            'Style', 'RadioButton', 'Tag', 'None', ...
            'String', 'Preserve', 'Enable', 'on', 'Tooltip', ...
            'Don'' write any tags to the data or clear existing tags', ...
            'Units','normalized', ...
            'Callback', @rewriteCallback, ...
            'Position', [0.1 0.2 0.8 0.1]);
    end % createRewriteGroupPanel


    function createButtonPanel()
        % Create the button panel on the side of GUI
        rewriteGroupPanel = uipanel('BorderType','none', ...
            'BackgroundColor',[.94 .94 .94],...
            'FontSize',12,...
            'Position',[0.6 0 .4 .2]);
        uicontrol('Parent', rewriteGroupPanel, ...
            'Style', 'pushbutton', 'Tag', 'OkayButton', ...
            'String', 'Okay', 'Enable', 'on', 'Tooltip', ...
            'Save the current configuration in a file', ...
            'Units','normalized', ...
            'Callback', {@okayCallback}, ...
            'Position',[0.025 0.3 0.45 0.4]);
        uicontrol('Parent', rewriteGroupPanel, ...
            'Style', 'pushbutton', 'Tag', 'CancelButton', ...
            'String', 'Cancel', 'Enable', 'on', 'Tooltip', ...
            'Cancel the directory tagging', ...
            'Units','normalized', ...
            'Callback', {@cancelCallback}, ...
            'Position',[0.515 0.3 0.45 0.4]);
    end % createButtonPanel

    function browseSaveTagsCallback(src, eventdata, saveTagsCtrl, myTitle) %#ok<INUSL>
        % Callback for browse button sets a directory for control
        startPath = get(saveTagsCtrl, 'String');
        if isempty(startPath) || ~ischar(startPath) || ~isdir(startPath)
            startPath = pwd;
        end
        dName = uigetdir(startPath, myTitle);  % Get
        if ~isempty(dName) && ischar(dName) && isdir(dName)
            saveMapFile = fullfile(dName, 'fMap.mat');
            set(saveTagsCtrl, 'String', saveMapFile);
        end
    end % browseSaveTagsCallback

    function browseTagsCallback(src, eventdata, tagsCtrl, myTitle) %#ok<INUSL>
        % Callback for browse button sets a directory for control
        [tFile, tPath] = uigetfile({'*.mat', 'MATLAB Files (*.mat)'}, myTitle);
        baseMap = fullfile(tPath, tFile);
        set(tagsCtrl, 'String', baseMap);
    end % browseTagsCallback

    function cancelCallback(src, eventdata)  %#ok<INUSD>
        % Callback for browse button sets a directory for control
        baseMap = '';
        cancelled = true;
        preservePrefix = false;
        rewriteOption = 'Both';
        saveMapFile = '';
        selectOption = true;
        useGUI = true;
        rewriteCtrl = '';
        editXmlCtrl = '';
        close(inputFig);
    end % browseTagsCallback

    function okayCallback(src, eventdata)  %#ok<INUSD>
        % Callback for closing GUI window
        cancelled = false;
        close(inputFig);
    end % okayCallback

    function saveTagsCtrlCallback(hObject, eventdata, saveTagsCtrl) %#ok<INUSD>
        % Callback for user directly editing directory control textbox
        saveMapFile = get(hObject, 'String');
    end % saveTagsCtrlCallback

    function preservePrefixCallback(src, eventdata) %#ok<INUSD>
        preservePrefix = get(src, 'Max') == get(src, 'Value');
    end % preservePrefixCallback

    function rewriteCallback(src, eventdata)    %#ok<INUSD>
        % Callback for the updateType button group
        if ~isempty(rewriteCtrl)
            set(rewriteCtrl, 'Value', get(rewriteCtrl, 'Min'));
        end
        rewriteCtrl = src;
        rewriteOption = lower(get(src, 'Tag'));
    end % rewriteCallback

    function selectCallback(src, eventdata) %#ok<INUSD>
        selectOption = get(src, 'Max') == get(src, 'Value');
    end % selectCallback

    function tagsCtrlCallback(hObject, eventdata, tagsCtrl) %#ok<INUSD>
        % Callback for user directly editing directory control textbox
        tagsFile = get(hObject, 'String');
        if isempty(typeMap.loadTagFile(tagsFile))
            warndlg([ tagsFile ' does not contain an typeMap object'], 'modal');
            set(hObject, 'String', baseMap);
        else
            baseMap = tagsFile;
        end
    end % tagsCtrlCallback

    function useGUICallback(src, eventdata) %#ok<INUSD>
        useGUI = get(src, 'Max') == get(src, 'Value');
        if ~useGUI
            editXml = false;
            set(editXmlCtrl, 'Enable', 'off', 'Value', ...
                get(editXmlCtrl, 'Min'));
            preservePrefix = false;
            set(preservePrefixCtrl, 'Enable', 'off', 'Value', ...
                get(preservePrefixCtrl, 'Min'));
        else
            set(editXmlCtrl, 'Enable', 'on');
            set(preservePrefixCtrl, 'Enable', 'on');
        end
    end % useGUICallback

    function editXmlCallback(src, eventdata) %#ok<INUSD>
        editXml = get(src, 'Max') == get(src, 'Value');
    end % editXmlCallback

    function browseDirCallback(src, eventdata, dirCtrl, myTitle) %#ok<INUSL>
        % Callback for browse button sets a directory for control
        startPath = get(dirCtrl, 'String');
        if isempty(startPath) || ~ischar(startPath) || ~isdir(startPath)
            startPath = pwd;
        end
        dName = uigetdir(startPath, myTitle);  % Get
        if ~isempty(dName) && ischar(dName) && isdir(dName)
            set(dirCtrl, 'String', dName);
            inDir = dName;
        end
    end % browseDirCallback

    function dirCtrlCallback(hObject, eventdata) %#ok<INUSD>
        % Callback for user directly editing directory control textbox
        directoryName = get(hObject, 'String');
        if isdir(directoryName)
            inDir = directoryName;
        else  % if user entered invalid directory reset back
            set(hObject, 'String', inDir);
        end
    end % dirCtrlCallback

    function doSubDirsCallback(src, eventdata) %#ok<INUSD>
        doSubDirs = get(src, 'Max') == get(src, 'Value');
    end % useGUICallback

    function writeTagsCallback(src, eventdata) %#ok<INUSD>
        writeTags = get(src, 'Max') == get(src, 'Value');
    end % writeTagsCallback

end % tagdir_input