% tagstudy_input
% GUI for input needed to create inputs for tagstudy
%
% Usage:
%   >>  tagstudy_input()
%
% Description:
% tagstudy_input() brings up a GUI for input needed to create inputs for
% tagstudy
%
% Function documentation:
% Execute the following in the MATLAB command window to view the function
% documentation for tagstudy_input:
%
%    doc tagstudy_input
% See also: tagstudy, pop_tagstudy
%
% Copyright (C) Kay Robbins and Thomas Rognon, UTSA, 2011-2013,
% krobbins@cs.utsa.edu
%
% This program is free software; you can redistribute it and/or modify
% it under the terms of the GNU General Public License as published by
% the Free Software Foundation; either version 2 of the License, or
% (at your option) any later version.
%
% This program is distributed in the hope that it will be useful,
% but WITHOUT ANY WARRANTY; without even the implied warranty of
% MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
% GNU General Public License for more details.
%
% You should have received a copy of the GNU General Public License
% along with this program; if not, write to the Free Software
% Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
%
% $Log: tagstudy_input.m,v $
% $Revision: 1.0 21-Apr-2013 09:25:25 krobbins $
% $Initial version $
%

function [studyFile, baseMap, editXml, preservePrefix, ...
    rewriteOption, saveDatasets, saveMapFile,  selectOption, useGUI, ...
    writeTags, cancelled] =  tagstudy_input()

% Setup the variables used by the GUI
baseMap = '';
cancelled = true;
preservePrefix = false;
editXml = false;
rewriteOption = 'Both';
writeButtonGroup = '';
editXmlCtrl = '';
saveDatasets = true;
saveMapFile = '';
selectOption = true;
studyFile = '';
useGUI = true;
title = 'Inputs for tagging EEG study';
writeTags = true;
inputFig = figure( ...
    'Color', [.94 .94 .94], ...
    'MenuBar', 'none', ...
    'Name', title, ...
    'NextPlot', 'add', ...
    'NumberTitle','off', ...
    'Resize', 'on', ...
    'Tag', title, ...
    'Toolbar', 'none', ...
    'Visible', 'off', ...
    'WindowStyle', 'modal');
createLayout();
movegui(inputFig); % Make sure it is visible
uiwait(inputFig);

    function browseSaveTagsCallback(~, ~)
        % Callback for browse button sets a directory for control
        [file,path] = uiputfile({'*.mat', 'MATLAB Files (*.mat)'}, ...
            'Save field map', 'fMap.mat');
        if file ~= 0
            saveMapFile = fullfile(path, file);
            set(findobj('Tag', 'SaveTags'), 'String', saveMapFile);
        end
    end % browseSaveTagsCallback

    function browseTagsCallback(~, ~)
        % Callback for browse button sets a directory for control
        [file, path] = uigetfile({'*.mat', 'MATLAB Files (*.mat)'}, ...
            'Browse for base tags');
        baseMap = fullfile(path, file);
        set(findobj('Tag', 'BaseTags'), 'String', baseMap);
    end % browseTagsCallback

    function createLayout()
        createBrowsePanel();
        createWriteGroupPanel();
        createOptionsGroupPanel();
        createButtonPanel();
    end

    function createBrowsePanel()
        browsePanel = uipanel('BorderType','none', ...
            'BackgroundColor',[.94 .94 .94],...
            'FontSize',12,...
            'Position',[0 .7 1 .3]);
        uicontrol('Parent', browsePanel, ...
            'Style','text', 'String', 'Study file', ...
            'Units','normalized',...
            'HorizontalAlignment', 'Left', ...
            'Position', [0.015 0.8 0.1 0.13]);
        uicontrol('Parent', browsePanel, ...
            'Style','text', 'String', 'Base tags', ...
            'Units','normalized',...
            'HorizontalAlignment', 'Left', ...
            'Position', [0.015 0.5 0.12 0.13]);
        uicontrol('Parent', browsePanel, ...
            'Style','text', 'String', 'Save tags', ...
            'Units','normalized',...
            'HorizontalAlignment', 'Left', ...
            'Position', [0.015 .2 0.12 0.13]);
        uicontrol('Parent', browsePanel, 'Style', 'edit', ...
            'BackgroundColor', 'w', 'HorizontalAlignment', 'Left', ...
            'Tag', 'StudyEdit', 'String', '', ...
            'TooltipString', ...
            'EEG study file name', ...
            'Units','normalized',...
            'Callback', @studyCtrlCallback, ...
            'Position', [0.15 0.7 0.6 0.25]);
        uicontrol('Parent', browsePanel, 'style', 'edit', ...
            'BackgroundColor', 'w', 'HorizontalAlignment', 'Left', ...
            'Tag', 'BaseTagsEdit', 'String', '', ...
            'TooltipString', ...
            'Complete path for loading the consolidated event tags', ...
            'Units','normalized',...
            'Callback', @tagsCtrlCallback, ...
            'Position', [0.15 0.4 0.6 0.25]);
        uicontrol('Parent', browsePanel, 'Style', 'edit', ...
            'BackgroundColor', 'w', 'HorizontalAlignment', 'Left', ...
            'Tag', 'SaveTags', 'String', '', ...
            'TooltipString', ...
            'Complete path for saving the consolidated event tags', ...
            'Units','normalized',...
            'Callback', @saveTagsCtrlCallback, ...
            'Position', [0.15 0.1 0.6 0.25]);
        uicontrol('Parent', browsePanel, ...
            'string', 'Browse', ...
            'style', 'pushbutton', 'TooltipString', ...
            'Press to bring up file chooser chooser', ...
            'Units','normalized',...
            'Callback', @browseStudyCallback, ...
            'Position', [0.775 0.7 0.21 0.25]);
        uicontrol('Parent', browsePanel, ...
            'string', 'Browse', 'style', 'pushbutton', ...
            'TooltipString', 'Press to choose BaseTags file', ...
            'Units','normalized',...
            'Callback', @browseTagsCallback, ...
            'Position', [0.775 0.4 0.21 0.25]);
        uicontrol('Parent', browsePanel, ...
            'string', 'Browse', 'style', 'pushbutton', ...
            'TooltipString', 'Press to find directory to save tags object', ...
            'Units','normalized',...
            'Callback', @browseSaveTagsCallback, ...
            'Position', [0.775 0.1 0.21 0.25]);
    end % createBrowsePanel

    function createOptionsGroupPanel()
        % Create the button panel on the side of GUI
        optionGroupPanel = uipanel('BackgroundColor',[.94,.94,.94],...
            'FontSize',12,...
            'Title','Other options', ...
            'Position',[0.535 .2 .45 .5]);
        uicontrol('Parent', optionGroupPanel, ...
            'Style', 'CheckBox', 'Tag', 'SaveAllCb', ...
            'String', 'Save to study dataset files', 'Enable', 'on', 'Tooltip', ...
            'If checked, save tags to study datasets in addition to study file', ...
            'Value', 1, ...
            'Units','normalized', ...
            'Callback', @saveCallback, ...
            'Position', [0.1 0.8 0.8 0.1]);
        uicontrol('Parent', optionGroupPanel, ...
            'Style', 'CheckBox', 'Tag', 'UseGUICB', ...
            'String', 'Use GUI to edit tags', 'Enable', 'on', 'Tooltip', ...
            'If checked, use GUI to edit consolidated tags', ...
            'Units','normalized', ...
            'Value', 1, ...
            'Callback', @useGUICallback, ...
            'Position', [0.1 0.65 0.8 0.1]);
        uicontrol('Parent', optionGroupPanel, ...
            'Style', 'CheckBox', 'Tag', 'SelectFieldsCB', ...
            'String', 'Use GUI to select fields to tag', 'Enable', 'on', 'Tooltip', ...
            'If checked, use GUI to select which fields to tag', ...
            'Units','normalized', ...
            'Value', 1, ...
            'Callback', @selectCallback, ...
            'Position', [0.1 0.5 0.8 0.1]);
        uicontrol('Parent', optionGroupPanel, ...
            'Style', 'CheckBox', 'Tag', 'EditXMLCB', ...
            'String', 'XML containing schema can be edited', 'Enable', 'on', 'Tooltip', ...
            'If checked, XML containing all of the schema tags can be edited', ...
            'Units','normalized', ...
            'Value', 0, ...
            'Callback', @editXmlCallback, ...
            'Position', [0.1 0.35 0.8 0.1]);
        uicontrol('Parent', optionGroupPanel, ...
            'Style', 'CheckBox', 'Tag', 'PreservePrefixCB', ...
            'String', 'Preserve tag prefixes', 'Enable', 'on', 'Tooltip', ...
            'If checked, do not consolidate tags that share prefixes', ...
            'Units','normalized', ...
            'Value', 0, ...
            'Callback', @preservePrefixCallback, ...
            'Position', [0.1 0.2 0.8 0.1]);
    end % createOptionsGroupPanel

    function createWriteGroupPanel()
        % Create the button panel on the side of GUI
        writeButtonGroup = uibuttongroup('BackgroundColor',[.94,.94,.94],...
            'FontSize',12,...
            'Title','Data precision save options', ...
            'Tag', 'abc', ...
            'SelectionChangeFcn', @rewriteCallback, ...
            'Position',[0.015 .2 .45 .5]);
        uicontrol('Parent', writeButtonGroup, ...
            'Style', 'RadioButton', 'Tag', 'Double', ...
            'String', 'Double (.set file)', 'Enable', 'On', ...
            'Tooltip', 'If selected, save the data as double precision and the dataset in a .set file', ...
            'Units','normalized', ...
            'Position', [0.1 0.8 0.8 0.1]);
        uicontrol('Parent', writeButtonGroup, ...
            'Style', 'RadioButton', 'Tag', 'SingleOne', ...
            'String', 'Single (.set file)', 'Enable', 'on', 'Tooltip', ...
            'If selected, save the data as single precision and the dataset in a .set file', ...
            'Units','normalized', ...
            'Position', [0.1 0.6 0.8 0.1]);
        uicontrol('Parent', writeButtonGroup, ...
            'Style', 'RadioButton', 'Tag', 'SingleTwo', ...
            'String', 'Single (.set and .fdt)', 'Enable', 'on', 'Tooltip', ...
            'If selected, save the data as single precision and the dataset in a .set and .fdt file', ...
            'Units','normalized', ...
            'Position', [0.1 0.4 0.8 0.1]);
        preserve = uicontrol('Parent', writeButtonGroup, ...
            'Style', 'RadioButton', 'Tag', 'Preserve', ...
            'String', 'Preserve', 'Enable', 'on', 'Tooltip', ...
            'If selected, preserve the data precision and preserve the way that the dataset is saved.', ...
            'Units','normalized', ...
            'Position', [0.1 0.2 0.8 0.1]);
        set(preserve, 'Value', get(preserve, 'Max'));
    end % createRewriteGroupPanel


    function createButtonPanel()
        % Create the button panel on the side of GUI
        buttonPanel = uipanel('BorderType','none', ...
            'BackgroundColor',[.94 .94 .94],...
            'FontSize',12,...
            'Position',[0.6 0 .4 .2]);
        uicontrol('Parent', buttonPanel, ...
            'Style', 'pushbutton', 'Tag', 'OkayButton', ...
            'String', 'Okay', 'Enable', 'on', 'Tooltip', ...
            'Save the current configuration in a file', ...
            'Units','normalized', ...
            'Callback', {@okayCallback}, ...
            'Position',[0.025 0.3 0.45 0.4]);
        uicontrol('Parent', buttonPanel, ...
            'Style', 'pushbutton', 'Tag', 'CancelButton', ...
            'String', 'Cancel', 'Enable', 'on', 'Tooltip', ...
            'Cancel the directory tagging', ...
            'Units','normalized', ...
            'Callback', {@cancelCallback}, ...
            'Position',[0.515 0.3 0.45 0.4]);
    end % createButtonPanel

    function browseStudyCallback(~, ~)
        % Callback for browse button sets a directory for control
        [file, filePath] = uigetfile({'*.study', 'Study files(*.study)'}, ...
            'Browse for study file');
        file = fullfile(filePath, file);
        if file ~= 0
            set(findobj('Tag', 'StudyEdit'), 'String', file);
            studyFile = file;
        end
    end % browseStudyCallback

    function cancelCallback(src, eventdata)  %#ok<INUSD>
        % Callback for browse button sets a directory for control
        baseMap = '';
        cancelled = true;
        preservePrefix = false;
        rewriteOption = 'Both';
        saveDatasets = true;
        saveMapFile = '';
        selectOption = true;
        studyFile = '';
        useGUI = true;
        close(inputFig);
    end % cancelTagsCallback

    function okayCallback(~, ~)
        % Callback for closing GUI window
        cancelled = false;
        close(inputFig);
    end % okayCallback

    function preservePrefixCallback(src, ~)
        preservePrefix = get(src, 'Max') == get(src, 'Value');
    end % preservePrefixCallback

    function rewriteCallback(src, ~) 
        rewriteOption = get(get(src, 'SelectedObject'), 'Tag');
    end % rewriteCallback

    function saveCallback(src, ~) 
        saveDatasets = get(src, 'Max') == get(src, 'Value');
        if ~saveDatasets
            set(findall(writeButtonGroup, '-property', 'Enable'), ...
                'Enable', 'off')
        else
            set(findall(writeButtonGroup, '-property', 'Enable'), ...
                'Enable', 'on')
        end
    end % saveAllCallback

    function saveTagsCtrlCallback(src, ~)
        % Callback for user directly editing directory control textbox
        saveMapFile = get(src, 'String');
    end % tagsCtrlCallback

    function selectCallback(src, ~) 
        selectOption = get(src, 'Max') == get(src, 'Value');
    end % selectCallback

    function studyCtrlCallback(src, ~) 
        % Callback for user directly editing directory control textbox
        study = get(src, 'String');
        if exist(study, 'file')
            studyFile = study;
        else  % if user entered invalid directory reset back
            set(src, 'String', studyFile);
        end
    end % dirCtrlCallback

    function tagsCtrlCallback(src, ~)
        % Callback for user directly editing directory control textbox
        baseMap = get(src, 'String');
    end % tagsCtrlCallback

    function useGUICallback(src, ~)
        useGUI = get(src, 'Max') == get(src, 'Value');
        if ~useGUI
            set(findobj('Tag', 'SelectFieldsCB'), 'Enable', 'off');
            set(findobj('Tag', 'EditXMLCB'), 'Enable', 'off');
            set(findobj('Tag', 'PreservePrefixCB'), 'Enable', 'off');
        else
            set(findobj('Tag', 'SelectFieldsCB'), 'Enable', 'on');
            set(findobj('Tag', 'EditXMLCB'), 'Enable', 'on');
            set(findobj('Tag', 'PreservePrefixCB'), 'Enable', 'on');
        end
    end % useGUICallback

    function editXmlCallback(src, eventdata) %#ok<INUSD>
        editXml = get(src, 'Max') == get(src, 'Value');
    end % editXmlCallback

end % tagstudy_input