function createTagValidationLayout(tab)
hed = '';
tags = '';
ouput = '';
columns = '';
hedCtrl = '';
tagsCtrl = '';
outputCtrl = '';
header = true;
extensionAllowed = true;
createPanel(tab);

    function browseHedCallback(src, eventdata, hedCtrl, ...
            myTitle) %#ok<INUSL>
        % Callback for 'Browse' button that sets the 'HED' editbox
        [tFile, tPath] = uigetfile({'*.xml', 'xml Files (*.xml)'}, ...
            myTitle);
        if tFile ~= 0
            hed = fullfile(tPath, tFile);
            set(hedCtrl, 'String', hed);
        end
    end % browseHedCallback

    function browseOutputCallback(src, eventdata, ...
            outputTxtCtrl, myTitle) %#ok<INUSL>
        % Callback for 'Browse' button that sets the 'Output' editbox
        startPath = get(outputTxtCtrl, 'String');
        if isempty(startPath) || ~ischar(startPath) || ~isdir(startPath)
            startPath = pwd;
        end
        dName = uigetdir(startPath, myTitle);
        if dName ~=0
            setOutput(dName);
        end
    end % browseOutputCallback

    function browseTagsCallback(src, eventdata, tagsCtrl, ...
            myTitle) %#ok<INUSL>
        % Callback for 'Browse' button that sets the 'Tags' editbox
        [tFile, tPath] = uigetfile({'*.txt', 'txt Files (*.txt)'}, ...
            myTitle);
        if tFile ~= 0
            tags = fullfile(tPath, tFile);
            set(tagsCtrl, 'String', tags);
            setOutput(tPath);
        end
    end % browseTagsCallback

    function createButtons(panel)
        % Creates the buttons in the panel
        uicontrol('Parent', panel, ...
            'String', 'Browse', ...
            'Style', 'pushbutton', ...
            'TooltipString', 'Press to choose HED XML file', ...
            'Units','normalized',...
            'Callback', {@browseHedCallback, ...
            hedCtrl, 'Browse for HED XML file'}, ...
            'Position', [0.775 0.85 0.2 0.1]);
        uicontrol('Parent', panel, ...
            'String', 'Browse', ...
            'Style', 'pushbutton', ...
            'TooltipString', 'Press to choose HED tag file', ...
            'Units','normalized',...
            'Callback', {@browseTagsCallback, ...
            tagsCtrl, 'Browse for tag file'}, ...
            'Position', [0.775 0.7 0.2 0.1]);
        uicontrol('Parent', panel, ...
            'String', 'Browse', ...
            'Style', 'pushbutton', ...
            'TooltipString', ...
            'Press to choose output directory', ...
            'Units','normalized',...
            'Callback', {@browseOutputCallback, ...
            outputCtrl, ...
            'Browse for ouput directory'}, ...
            'Position', [0.775 0.55 0.2 0.1]);
        uicontrol('Parent', panel, ...
            'String', 'Validate', ...
            'Style', 'pushbutton', ...
            'TooltipString', ...
            'Presse to validate HED event tags', ...
            'Units','normalized',...
            'Callback', {@validateTagsCallback}, ...
            'Position', [0.775 0.05 0.2 0.1]);
    end % createButtons

    function createCheckboxes(panel)
        % Creates the checkboxes in the panel
        uicontrol('Parent', panel, ...
            'Style', 'checkbox', ...
            'HorizontalAlignment', 'Left', ...
            'String', '', ...
            'Value', 1, ...
            'TooltipString', 'Tag file has a header', ...
            'Units','normalized',...
            'Callback', {@headerCallback}, ...
            'Position', [0.15 0.25 0.3 0.1]);
        uicontrol('Parent', panel, ...
            'Style', 'checkbox', ...
            'HorizontalAlignment', 'Left', ...
            'String', '', ...
            'Value', 1, ...
            'TooltipString', 'Extension allowed tags are enabled', ...
            'Units','normalized',...
            'Callback', {@extensionAllowedCallback}, ...
            'Position', [0.15 0.1 0.3 0.1]);
    end % createCheckboxes

    function createEditBoxes(panel)
        % Creates the edit boxes in the panel
        hedCtrl = uicontrol('Parent', panel, ...
            'Style', 'edit', ...
            'BackgroundColor', 'w', ...
            'HorizontalAlignment', 'Left', ...
            'String', '', ...
            'TooltipString', 'HED XML file', ...
            'Units','normalized',...
            'Callback', {@hedCtrlCallback}, ...
            'Position', [0.15 0.85 0.6 0.1]);
        tagsCtrl = uicontrol('Parent', panel, ...
            'Style', 'edit', ...
            'BackgroundColor', 'w', ...
            'HorizontalAlignment', 'Left', ...
            'String', '', ...
            'TooltipString', 'HED tag file', ...
            'Units','normalized',...
            'Callback', {@tagsCtrlCallback}, ...
            'Position', [0.15 0.7 0.6 0.1]);
        outputCtrl = uicontrol('Parent', panel, ...
            'Style', 'edit', ...
            'BackgroundColor', 'w', ...
            'HorizontalAlignment', 'Left', ...
            'String', '', ...
            'TooltipString', 'Output directory', ...
            'Units','normalized',...
            'Callback', {@outputCtrlCallback}, ...
            'Position', [0.15 0.55 0.6 0.1]);
        uicontrol('Parent', panel, ...
            'Style', 'edit', ...
            'BackgroundColor', 'w', ...
            'HorizontalAlignment', 'Left', ...
            'Tag', 'validateHedXmlEdit', ...
            'String', '', ...
            'TooltipString', ...
            'HED tag columns (single value or comma sepearted)', ...
            'Units','normalized',...
            'Callback', {@columnsCtrlCallback}, ...
            'Position', [0.15 0.4 0.3 0.1]);
    end % createEditBoxes

    function createLabels(panel)
        % Creates the labels in the panel
        uicontrol('parent', panel, ...
            'Style', 'Text', ...
            'Units', 'normalized', ...
            'String', 'HED', ...
            'HorizontalAlignment', 'Left', ...
            'Position', [0.04 0.8 0.12 0.12]);
        uicontrol('parent', panel, ...
            'Style', 'Text', ...
            'Units', 'normalized', ...
            'String', 'Tags', ...
            'HorizontalAlignment', 'Left', ...
            'Position', [0.04 0.65 0.12 0.12]);
        uicontrol('parent', panel, ...
            'Style', 'Text', ...
            'Units', 'normalized', ...
            'String', 'Output', ...
            'HorizontalAlignment', 'Left', ...
            'Position', [0.04 0.5 0.12 0.12]);
        uicontrol('parent', panel, ...
            'Style', 'Text', ...
            'Units', 'normalized', ...
            'String', 'Column(s)', ...
            'HorizontalAlignment', 'Left', ...
            'Position', [0.04 0.35 0.12 0.12]);
        uicontrol('parent', panel, ...
            'Style', 'Text', ...
            'Units', 'normalized', ...
            'String', 'Header', ...
            'HorizontalAlignment', 'Left', ...
            'Position', [0.04 0.2 0.12 0.12]);
        uicontrol('parent', panel, ...
            'Style', 'Text', ...
            'Units', 'normalized', ...
            'String', 'Extension Allowed', ...
            'HorizontalAlignment', 'Left', ...
            'Position', [0.04 0.05 0.12 0.12]);
    end % createLabels

    function createPanel(tab)
        % Creates the 'Validate Tags' tab panel
        panel = uipanel('Parent', tab, ...
            'BorderType', 'none', ...
            'BackgroundColor', [.94 .94 .94], ...
            'FontSize', 12, ...
            'Position', [0 0 1 1]);
        createLabels(panel);
        createEditBoxes(panel);
        createCheckboxes(panel);
        createButtons(panel);
    end % createPanel

    function columnsCtrlCallback(src, eventdata) %#ok<INUSD>
        % Callback for user directly editing the 'Columns' editbox
        columns = str2double(get(src, 'String'));
    end % columnsCtrlCallback

    function extensionAllowedCallback(src, eventdata) %#ok<INUSD>
        % Callback for user directly editing the 'Extension Allowed'
        % checkbox
        extensionAllowed = get(src, 'Max') == get(src, 'Value');
    end % extensionAllowedCallback

    function headerCallback(src, eventdata) %#ok<INUSD>
        % Callback for user directly editing the 'Header' checkbox
        header = get(src, 'Max') == get(src, 'Value');
    end % headerCallback

    function hedCtrlCallback(src, eventdata) %#ok<INUSD>
        % Callback for user directly editing the 'HED' editbox
        hed = get(src, 'String');
    end % hedCtrlCallback

    function outputCtrlCallback(src, eventdata) %#ok<INUSD>
        % Callback for user directly editing the 'Output' editbox
        ouput = get(src, 'String');
    end % outputCtrlCallback

    function setOutput(dName)
        % Sets the 'Output' edit box based on the 'Tags' editbox
        ouput = dName;
        set(outputCtrl, 'String', ouput);
    end % setOutput

    function tagsCtrlCallback(src, eventdata) %#ok<INUSD>
        % Callback for user directly editing the 'Tags' editbox
        tags = get(src, 'String');
    end % tagsCtrlCallback

    function validateTagsCallback(src, eventdata) %#ok<INUSD>
        % Callback for the 'Validate' button
        if isempty(hed)
            errordlg('HED XML file is empty');
        elseif isempty(tags)
            errordlg('HED Tag file is empty');
        elseif isempty(ouput)
            errordlg('Output directory is empty');
        elseif isempty(columns)
            errordlg('Tag columns are empty');
        else
            wb = waitbar(.5,'Please wait...');
            try
                validatetags(hed, tags, columns, 'Output', ouput, ...
                    'Header', header, 'ExtensionAllowed', ...
                    extensionAllowed);
                msgbox('Validation complete');
            catch
                errordlg('Validation failed');
            end
            close(wb);
        end
    end % validateTagsCallback

end % createTagValidationLayout