function createHedValidationLayout(tab)
schema = '';
hed = '';
output = '';
schemaCtrl = '';
hedCtrl = '';
outputCtrl = '';
createPanel(tab);

    function browseHedCallback(src, eventdata, hedXmlCtrl, ...
            myTitle) %#ok<INUSL>
        % Callback for 'Browse' button that sets the 'HED' editbox
        [fName, dName] = uigetfile({'*.xml', 'xml Files (*.xml)'}, ...
            myTitle);
        if fName ~= 0
            hed = fullfile(dName, fName);
            set(hedXmlCtrl, 'String', hed);
            setOutput(dName);
        end
    end % browseHedCallback

    function browseOutputCallback(src, eventdata, errorCtrl, ...
            myTitle) %#ok<INUSL>
        % Callback for 'Browse' button that sets the 'Output' editbox
        startPath = get(outputCtrl, 'String');
        if isempty(startPath) || ~ischar(startPath) || ~isdir(startPath)
            startPath = pwd;
        end
        dName = uigetdir(startPath, myTitle);  % Get
        if dName ~=0
            setOutput(dName);
        end
    end % browseOutputCallback

    function browseSchemaCallback(src, eventdata, schemaCtrl, ...
            myTitle) %#ok<INUSL>
        % Callback for 'Browse' button that sets the 'Schema' editbox
        [fName, dName] = uigetfile({'*.xsd', 'xsd Files (*.xsd)'}, ...
            myTitle);
        if fName ~= 0
            schema = fullfile(dName, fName);
            set(schemaCtrl, 'String', schema);
        end
    end % browseSchemaCallback

    function createButtons(panel)
        % Creates the buttons in the panel
        uicontrol('Parent', panel, ...
            'String', 'Browse', ...
            'Style', 'pushbutton', ...
            'TooltipString', 'Press to choose HED XML schema file', ...
            'Units','normalized',...
            'Callback', {@browseSchemaCallback, ...
            schemaCtrl, ...
            'Browse for HED XML schema file'}, ...
            'Position', [0.775 0.85 0.2 0.1]);
        uicontrol('Parent', panel, ...
            'String', 'Browse', ...
            'Style', 'pushbutton', ...
            'TooltipString', 'Press to choose HED XML file', ...
            'Units','normalized',...
            'Callback', {@browseHedCallback, ...
            hedCtrl, 'Browse for HED XML file'}, ...
            'Position', [0.775 0.7 0.2 0.1]);
        uicontrol('Parent', panel, ...
            'String', 'Browse', ...
            'Style', 'pushbutton', ...
            'TooltipString', ...
            'Press to choose output file directory', ...
            'Units','normalized',...
            'Callback', {@browseOutputCallback, ...
            outputCtrl, ...
            'Browse for output file directory'}, ...
            'Position', [0.775 0.55 0.2 0.1]);
        uicontrol('Parent', panel, ...
            'String', 'Validate', ...
            'Style', 'pushbutton', ...
            'TooltipString', 'Validate HED XML against HED XML schema', ...
            'Units','normalized',...
            'Callback', {@validateHedCallback}, ...
            'Position', [0.775 0.05 0.2 0.1]);
    end % createButtons

    function createEditBoxes(panel)
        % Creates the edit boxes in the panel
        schemaCtrl = uicontrol('Parent', panel, ...
            'Style', 'edit', ...
            'BackgroundColor', 'w', ...
            'HorizontalAlignment', 'Left', ...
            'String', '', ...
            'TooltipString', 'HED XML schema file', ...
            'Units','normalized',...
            'Callback', {@schemaCtrlCallback}, ...
            'Position', [0.15 0.85 0.6 0.1]);
        hedCtrl = uicontrol('Parent', panel, ...
            'Style', 'edit', ...
            'BackgroundColor', 'w', ...
            'HorizontalAlignment', 'Left', ...
            'String', '', ...
            'TooltipString', 'HED XML file', ...
            'Units','normalized',...
            'Callback', {@hedCtrlCallback}, ...
            'Position', [0.15 0.7 0.6 0.1]);
        outputCtrl = uicontrol('Parent', panel, ...
            'Style', 'edit', ...
            'BackgroundColor', 'w', ...
            'HorizontalAlignment', 'Left', ...
            'String', '', ...
            'TooltipString', 'Output file', ...
            'Units','normalized',...
            'Callback', {@outputCtrlCallback}, ...
            'Position', [0.15 0.55 0.6 0.1]);
    end % createEditBoxes

    function createLabels(panel)
        % Creates the labels in the panel
        uicontrol('parent', panel, ...
            'Style', 'Text', ...
            'Units', 'normalized', ...
            'String', 'Schema', ...
            'HorizontalAlignment', 'Left', ...
            'Position', [0.04 0.8 0.12 0.12]);
        uicontrol('parent', panel, ...
            'Style', 'Text', ...
            'Units', 'normalized', ...
            'String', 'HED', ...
            'HorizontalAlignment', 'Left', ...
            'Position', [0.04 0.65 0.12 0.12]);
        uicontrol('parent', panel, ...
            'Style', 'Text', ...
            'Units', 'normalized', ...
            'String', 'Output', ...
            'HorizontalAlignment', 'Left', ...
            'Position', [0.04 0.5 0.12 0.12]);
    end % createLabels

    function createPanel(tab)
        % Creates the hed validation panel
        panel = uipanel('Parent', tab, ...
            'BorderType', 'none', ...
            'BackgroundColor', [.94 .94 .94], ...
            'FontSize', 12, ...
            'Position', [0 0 1 1]);
        createLabels(panel);
        createEditBoxes(panel);
        createButtons(panel);
    end % createPanel

    function hedCtrlCallback(src, eventdata) %#ok<INUSD>
        % Callback for user directly editing the 'HED' editbox
        hed = get(src, 'String');
    end % hedCtrlCallback

    function outputCtrlCallback(src, eventdata) %#ok<INUSD>
        % Callback for user directly editing the 'Output' editbox
        output = get(src, 'String');
    end % outputCtrlCallback

    function schemaCtrlCallback(src, eventdata) %#ok<INUSD>
        % Callback for user directly editing the 'Schema' editbox
        schema = get(src, 'String');
    end % schemaCtrlCallback

    function setOutput(dName)
        % Sets the 'Output' edit box based on the 'HED' editbox
        output = dName;
        set(outputCtrl, 'String', output);
    end % setOutput

    function validateHedCallback(src, eventdata) %#ok<INUSD>
        % Callback for the 'Validate' button
        if isempty(schema)
            errordlg('HED XML schema file is empty');
        elseif isempty(hed)
            errordlg('HED XML file is empty');
        elseif isempty(output)
            errordlg('Output file is empty');
        else
            wb = waitbar(.5,'Please wait...');
            try
                validatehed(schema, hed, output)
                msgbox('Validation Complete');
            catch
                errordlg('Validation Failed');
            end
            close(wb);
        end
    end % validateHedCallback

end % createHedValidationLayout