function createReplaceTagsLayout(tab)
latestHED = 'HED 2.026';
remap = '';
tags = '';
output = '';
header = true;
columns = '';
remapCtrl = '';
tagsCtrl = '';
outputCtrl = '';
createPanel(tab);

    function browseOutputCallback(src, eventdata, replaceOutputCtrl, ...
            myTitle) %#ok<INUSL>
        % Callback for 'Browse' button that sets the 'Output' editbox
        startPath = get(replaceOutputCtrl, 'String');
        if isempty(startPath) || ~ischar(startPath) || ~isdir(startPath)
            startPath = pwd;
        end
        dName = uigetdir(startPath, myTitle);  
        if dName ~= 0
            setOutput(dName);
        end
    end % browseOutputCallback

    function browseRemapCallback(src, eventdata, replaceTxtCtrl, ...
            myTitle) %#ok<INUSL>
        % Callback for 'Browse' button that sets the 'Remap' editbox
        [tFile, tPath] = uigetfile({'*.txt', 'txt Files (*.txt)'}, ...
            myTitle);
        if tFile ~= 0
            remap = fullfile(tPath, tFile);
            set(replaceTxtCtrl, 'String', remap);
        end
    end % browseRemapCallback

    function browseTagsCallback(src, eventdata, replaceTagCtrl, ...
            myTitle) %#ok<INUSL>
        % Callback for 'Browse' button that sets the 'Tags' editbox
        [tFile, tPath] = uigetfile({'*.txt', 'txt Files (*.txt)'}, ...
            myTitle);
        if tFile ~= 0
            tags = fullfile(tPath, tFile);
            set(replaceTagCtrl, 'String', tags);
            setOutput(tPath);
        end
    end % browseTagsCallback

    function columnsCtrlCallback(src, eventdata) %#ok<INUSD>
        % Callback for user directly editing the 'Columns' editbox
        columns = str2double(get(src, 'String'));
    end % columnsCtrlCallback

    function createButtons(panel)
        % Creates the buttons in the panel
        uicontrol('Parent', panel, ...
            'String', 'Browse', ...
            'Style', 'pushbutton', ...
            'TooltipString', 'Press to choose HED remap file', ...
            'Units','normalized',...
            'Callback', {@browseRemapCallback, ...
            remapCtrl, ...
            'Browse for HED remap file'}, ...
            'Position', [0.775 0.85 0.2 0.1]);
        uicontrol('Parent', panel, ...
            'String', 'Browse', ...
            'Style', 'pushbutton', ...
            'TooltipString', 'Press to choose tag file', ...
            'Units','normalized',...
            'Callback', {@browseTagsCallback, ...
            tagsCtrl, 'Browse for tag file'}, ...
            'Position', [0.775 0.7 0.2 0.1]);
        uicontrol('Parent', panel, ...
            'String', 'Browse', ...
            'Style', 'pushbutton', ...
            'TooltipString', ...
            'Press to choose output file directory', ...
            'Units','normalized',...
            'Callback', {@browseOutputCallback, ...
            outputCtrl, ...
            'Browse for output file'}, ...
            'Position', [0.775 0.55 0.2 0.1]);
        uicontrol('Parent', panel, ...
            'String', 'Replace', ...
            'Style', 'pushbutton', ...
            'TooltipString', 'Replace tags based on remap file', ...
            'Units','normalized',...
            'Callback', {@replaceCallback}, ...
            'Position', [0.775 0.05 0.2 0.1]);
    end % createButtons

    function createEditBoxes(panel)
        % Creates the edit boxes in the panel
        uicontrol('Parent', panel, ...
            'Style', 'edit', ...
            'BackgroundColor', 'w', ...
            'HorizontalAlignment', 'Left', ...
            'Tag', 'validateHedXmlEdit', ...
            'String', '', ...
            'TooltipString', ...
            'The tag columns (single value or comma sepearted)', ...
            'Units','normalized',...
            'Callback', {@columnsCtrlCallback}, ...
            'Position', [0.15 0.4 0.3 0.1]);
        remapCtrl = uicontrol('Parent', panel, ...
            'Style', 'edit', ...
            'BackgroundColor', 'w', ...
            'HorizontalAlignment', 'Left', ...
            'String', '', ...
            'TooltipString', 'HED remap file', ...
            'Units','normalized',...
            'Callback', {@remapCtrlCallback}, ...
            'Position', [0.15 0.85 0.6 0.1]);
        tagsCtrl = uicontrol('Parent', panel, ...
            'Style', 'edit', ...
            'BackgroundColor', 'w', ...
            'HorizontalAlignment', 'Left', ...
            'String', '', ...
            'TooltipString', 'HED tag file', ...
            'Units','normalized',...
            'Callback', {@tagsCtrlCallback}, ...
            'Position', [0.15 0.7 0.6 0.1]);
        outputCtrl = uicontrol('Parent', panel, ...
            'Style', 'edit', ...
            'BackgroundColor', 'w', ...
            'HorizontalAlignment', 'Left', ...
            'String', '', ...
            'TooltipString', 'Output file', ...
            'Units','normalized',...
            'Callback', {@outputCtrlCallback}, ...
            'Position', [0.15 0.55 0.6 0.1]);
    end % createEditBoxes

    function createCheckboxes(panel)
        % Creates the checkboxes in the panel
        uicontrol('Parent', panel, ...
            'Style', 'checkbox', ...
            'HorizontalAlignment', 'Left', ...
            'String', '', ...
            'Value', 1, ...
            'TooltipString', 'Tag file has a header', ...
            'Units','normalized',...
            'Callback', {@headerCallback}, ...
            'Position', [0.15 0.25 0.3 0.1]);
    end % createCheckboxes

    function createLabels(panel)
        % Creates the labels in the panel
        uicontrol('parent', panel, ...
            'Style', 'Text', ...
            'Units', 'normalized', ...
            'String', 'Remap', ...
            'HorizontalAlignment', 'Left', ...
            'Position', [0.04 0.8 0.12 0.12]);
        uicontrol('parent', panel, ...
            'Style', 'Text', ...
            'Units', 'normalized', ...
            'String', 'Tags', ...
            'HorizontalAlignment', 'Left', ...
            'Position', [0.04 0.65 0.12 0.12]);
        uicontrol('parent', panel, ...
            'Style', 'Text', ...
            'Units', 'normalized', ...
            'String', 'Output', ...
            'HorizontalAlignment', 'Left', ...
            'Position', [0.04 0.5 0.12 0.12]);
        uicontrol('parent', panel, ...
            'Style', 'Text', ...
            'Units', 'normalized', ...
            'String', 'Column(s)', ...
            'HorizontalAlignment', 'Left', ...
            'Position', [0.04 0.35 0.12 0.12]);
        uicontrol('parent', panel, ...
            'Style', 'Text', ...
            'Units', 'normalized', ...
            'String', 'Header', ...
            'HorizontalAlignment', 'Left', ...
            'Position', [0.04 0.2 0.12 0.12]);
    end % createLabels

    function createPanel(tab)
        % Creates replace tags layout
        panel = uipanel('Parent', tab, ...
            'BorderType', 'none', ...
            'BackgroundColor', [.94 .94 .94], ...
            'FontSize', 12, ...
            'Position', [0 0 1 1]);
        createLabels(panel);
        createEditBoxes(panel);
        createCheckboxes(panel);
        createButtons(panel);
    end % createPanel

    function headerCallback(src, eventdata) %#ok<INUSD>
        % Callback for user directly editing the 'Header' checkbox
        header = get(src, 'Max') == get(src, 'Value');
    end % headerCallback

    function outputCtrlCallback(src, eventdata) %#ok<INUSD>
        % Callback for user directly editing the 'Output' editbox
        output = get(src, 'String');
    end % outputCtrlCallback

    function replaceCallback(src, eventdata) %#ok<INUSD>
        % Callback for the tag validation button
        % Callback for convert button
        if isempty(remap)
            errordlg('HED remap file is empty');
        elseif isempty(tags)
            errordlg('HED tag file is empty');
        elseif isempty(output)
            errordlg('Output is empty');
        elseif isempty(columns)
            errordlg('Columns are empty');
        else
            wb = waitbar(.5,'Please wait...');
            try
                replacetags(remap, tags, columns, ...
                    'Header', header, 'OutputFile', output);
                msgbox('Tag replacement complete');
            catch
                errordlg('Tag replacement failed');
            end
            close(wb);
        end
    end % replaceCallback

    function remapCtrlCallback(src, eventdata) %#ok<INUSD>
        % Callback for user directly editing the 'Remap' editbox
        remap = get(src, 'String');
    end % remapCtrlCallback

    function setOutput(dName)
        % Sets the 'Output' edit box based on the 'Tags' editbox
        if isempty(tags)
            output = fullfile(dName, ...
                [latestHED '_replace.txt']);
        else
            [~, file] = fileparts(tags);
            output = fullfile(dName, [file '_replace.txt']);
        end
        set(outputCtrl, 'String', output);
    end % setOutput

    function tagsCtrlCallback(src, eventdata) %#ok<INUSD>
        % Callback for user directly editing the 'Tags' editbox
        tags = get(src, 'String');
    end % tagsCtrlCallback

end % createReplaceTagsLayout