function createWikiConversionLayout(tab)
latestHED = 'HED 2.026';
wiki = '';
hed = '';
wikiCtrl = '';
hedCtrl = '';
createPanel(tab);

    function browseHedCallback(src, eventdata, hedXmlCtrl, ...
            myTitle) %#ok<INUSL>
        % Callback for 'Browse' button that sets the 'HED' editbox
        startPath = get(hedXmlCtrl, 'String');
        if isempty(startPath) || ~ischar(startPath) || ~isdir(startPath)
            startPath = pwd;
        end
        dName = uigetdir(startPath, myTitle);
        if dName ~= 0
            setHed(dName);
        end
    end % browseXmlCallback

    function browseWikiCallback(src, eventdata, wikiCtrl, ...
            myTitle) %#ok<INUSL>
        % Callback for 'Browse' button that sets the 'Wiki' editbox
        [fName, dName] = uigetfile({'*.txt', 'text Files (*.txt)'}, ...
            myTitle);
        if fName ~= 0
            wiki = fullfile(dName, fName);
            set(wikiCtrl, 'String', wiki);
            dName = dName(1:end-1);
            setHed(dName);
        end
    end % browseWikiCallback

    function conversionCallback(src, eventdata) %#ok<INUSD>
        % Callback for the 'Convert' button
        if isempty(wiki)
            errordlg('Wiki text file is empty');
        elseif isempty(hed)
            errordlg('HED XML file is empty');
        else
            wb = waitbar(.5,'Please wait...');
            try
                wiki2hed(wiki, hed);
                msgbox('Conversion Complete');
            catch
                errordlg('Conversion Failed');
            end
            close(wb);
        end
    end % conversionCallback

    function createButtons(panel)
        % Creates the buttons in the panel
        uicontrol('Parent', panel, ...
            'String', 'Browse', ...
            'Style', 'pushbutton', ...
            'TooltipString', 'Press to choose wiki text file', ...
            'Units','normalized',...
            'Callback', {@browseWikiCallback, ...
            wikiCtrl, 'Browse for wiki text file'}, ...
            'Position', [0.775 0.85 0.2 0.1]);
        uicontrol('Parent', panel, ...
            'String', 'Browse', ...
            'Style', 'pushbutton', ...
            'TooltipString', 'Press to choose HED XML file directory', ...
            'Units','normalized',...
            'Callback', {@browseHedCallback, ...
            hedCtrl, 'Browse for HED XML file dirctory'}, ...
            'Position', [0.775 0.7 0.2 0.1]);
        uicontrol('Parent', panel, ...
            'String', 'Convert', ...
            'Style', 'pushbutton', ...
            'TooltipString', ...
            'Converts a wiki text file to a HED XML file', ...
            'Units','normalized',...
            'Callback', {@conversionCallback}, ...
            'Position', [0.775 0.05 0.2 0.1]);
    end % createButtons

    function createEditBoxes(panel)
        % Creates the edit boxes in the panel
        wikiCtrl = uicontrol('Parent', panel, ...
            'Style', 'edit', ...
            'BackgroundColor', 'w', ...
            'HorizontalAlignment', 'Left', ...
            'String', '', ...
            'TooltipString', 'Wiki text file', ...
            'Units','normalized',...
            'Callback', {@wikiCtrlCallback}, ...
            'Position', [0.15 0.85 0.6 0.1]);
        hedCtrl = uicontrol('Parent', panel, ...
            'Style', 'edit', ...
            'BackgroundColor', 'w', ...
            'HorizontalAlignment', 'Left', ...
            'String', '', ...
            'TooltipString', 'HED XML file', ...
            'Units','normalized',...
            'Callback', {@hedCtrlCallback}, ...
            'Position', [0.15 0.7 0.6 0.1]);
    end % createEditBoxes

    function createLabels(panel)
        % Creates the labels in the panel
        uicontrol('parent', panel, ...
            'Style', 'Text', ...
            'Units', 'normalized', ...
            'String', 'Wiki', ...
            'HorizontalAlignment', 'Left', ...
            'Position', [0.04 0.8 0.12 0.12]);
        uicontrol('parent', panel, ...
            'Style', 'Text', ...
            'Units', 'normalized', ...
            'String', 'HED', ...
            'HorizontalAlignment', 'Left', ...
            'Position', [0.04 0.65 0.12 0.12]);
    end % createLabels

    function createPanel(tab)
        % Creates the tab panel
        panel = uipanel('Parent', tab, ...
            'BorderType', 'none', ...
            'BackgroundColor', [.94 .94 .94], ...
            'FontSize', 12, ...
            'Position', [0 0 1 1]);
        createLabels(panel);
        createEditBoxes(panel);
        createButtons(panel);
    end % createPanel

    function hedCtrlCallback(src, eventdata) %#ok<INUSD>
        % Callback for user directly editing the 'HED' editbox
        hed = get(src, 'String');
    end % hedCtrlCallback

    function setHed(dName)
        % Sets the 'HED' edit box based on the 'Wiki' editbox
        if isempty(wiki)
            hed = [dName, filesep, latestHED, '.xml'];
        else
            [~, fName] = fileparts(wiki);
            hed = [dName, filesep, fName, '.xml'];
        end
        set(hedCtrl, 'String', hed);
    end % setHed

    function wikiCtrlCallback(src, eventdata) %#ok<INUSD>
        % Callback for user directly editing the 'Wiki' editbox
        wiki = get(src, 'String');
    end % wikiCtrlCallback

end % createWikiConversionLayout