function createRemapTagsLayout(tab)
latestHED = 'HED 2.026';
mapFile = '';
tsvFile = '';
outputFile = '';
tsvTagColumns = '2';
mapCtrl = '';
tsvCtrl = '';
outputCtrl = '';
createPanel(tab);

    function browseOutputCallback(src, eventdata, replaceOutputCtrl, ...
            myTitle) %#ok<INUSL>
        % Callback for 'Browse' button that sets the 'Output' editbox
        startPath = get(replaceOutputCtrl, 'String');
        if isempty(startPath) || ~ischar(startPath) || ~isdir(startPath)
            startPath = pwd;
        end
        dName = uigetdir(startPath, myTitle);
        if dName ~= 0
            setOutput(dName);
        end
    end % browseOutputCallback

    function browseMapCallback(src, eventdata, replaceTxtCtrl, ...
            myTitle) %#ok<INUSL>
        % Callback for 'Browse' button that sets the 'Remap' editbox
        [tFile, tPath] = uigetfile({'*.txt', 'txt Files (*.txt)'}, ...
            myTitle);
        if tFile ~= 0
            mapFile = fullfile(tPath, tFile);
            set(replaceTxtCtrl, 'String', mapFile);
        end
    end % browseMapCallback

    function browseTagsCallback(src, eventdata, replaceTagCtrl, ...
            myTitle) %#ok<INUSL>
        % Callback for 'Browse' button that sets the 'Tags' editbox
        [tFile, tPath] = uigetfile({'*.txt', 'txt Files (*.txt)'}, ...
            myTitle);
        if tFile ~= 0
            tsvFile = fullfile(tPath, tFile);
            set(replaceTagCtrl, 'String', tsvFile);
            setOutput(tPath);
        end
    end % browseTagsCallback

    function columnsCtrlCallback(src, eventdata) %#ok<INUSD>
        % Callback for user directly editing the 'Columns' editbox
        tsvTagColumns = str2num(get(src, 'String')); %#ok<ST2NM>
    end % columnsCtrlCallback

    function createButtons(panel)
        % Creates the buttons in the panel
        uicontrol('Parent', panel, ...
            'String', 'Browse', ...
            'Style', 'pushbutton', ...
            'TooltipString', ['Press to choose tab-delimited input' ...
            ' file.'], ...
            'Units','normalized',...
            'Callback', {@browseTagsCallback, ...
            tsvCtrl, ...
            'Browse for HED remap file'}, ...
            'Position', [0.775 0.8 0.2 0.1]);
        uicontrol('Parent', panel, ...
            'String', 'Browse', ...
            'Style', 'pushbutton', ...
            'TooltipString', 'Press to choose remap file.', ...
            'Units','normalized',...
            'Callback', {@browseMapCallback, ...
            mapCtrl, 'Browse for tag file'}, ...
            'Position', [0.775 0.65 0.2 0.1]);
        uicontrol('Parent', panel, ...
            'String', 'Browse', ...
            'Style', 'pushbutton', ...
            'TooltipString', ...
            'Press to choose output file directory.', ...
            'Units','normalized',...
            'Callback', {@browseOutputCallback, ...
            outputCtrl, ...
            'Browse for output file'}, ...
            'Position', [0.775 0.5 0.2 0.1]);
        uicontrol('Parent', panel, ...
            'String', 'Help', ...
            'Style', 'pushbutton', ...
            'TooltipString', ...
            'Press for additional instructions.', ...
            'Units','normalized',...
            'Callback', {@helpCallback}, ...
            'Position', [0.775 .35 0.2 0.1]);
        uicontrol('Parent', panel, ...
            'String', 'Remap', ...
            'Style', 'pushbutton', ...
            'TooltipString', ['Replaces old HED tags with new HED' ...
            ' tags based on a remap file.'], ...
            'Units','normalized',...
            'Callback', {@replaceCallback}, ...
            'Position', [0.775 0.025 0.2 0.1]);
    end % createButtons

    function createEditBoxes(panel)
        % Creates the edit boxes in the panel
        tsvCtrl = uicontrol('Parent', panel, ...
            'Style', 'edit', ...
            'BackgroundColor', 'w', ...
            'HorizontalAlignment', 'Left', ...
            'String', '', ...
            'TooltipString', ['A tab-delimited input file containing' ...
            ' HED tags associated with a particular study or' ...
            ' experiment events.'], ...
            'Units','normalized',...
            'Callback', {@tsvCtrlCallback}, ...
            'Position', [0.15 0.8 0.6 0.1]);
        mapCtrl = uicontrol('Parent', panel, ...
            'Style', 'edit', ...
            'BackgroundColor', 'w', ...
            'HorizontalAlignment', 'Left', ...
            'Tag', 'validateHedXmlEdit', ...
            'String', '', ...
            'TooltipString', ['A tab-delimited remap file containing' ...
            ' two columns. The tags in the first column are replaced' ...
            ' with the tags in the second column when present in' ...
            ' the input file.'], ...
            'Units','normalized',...
            'Callback', {@mapCtrlCallback}, ...
            'Position', [0.15 0.65 0.6 0.1]);
        outputCtrl = uicontrol('Parent', panel, ...
            'Style', 'edit', ...
            'BackgroundColor', 'w', ...
            'HorizontalAlignment', 'Left', ...
            'String', '', ...
            'TooltipString', ['A output file with the second column' ...
            ' replacement tags in the remap file. The output file name' ...
            ' will have _remap appended to the input file name.'], ...
            'Units','normalized',...
            'Callback', {@outputCtrlCallback}, ...
            'Position', [0.15 0.5 0.6 0.1]);
        uicontrol('Parent', panel, ...
            'Style', 'edit', ...
            'BackgroundColor', 'w', ...
            'HorizontalAlignment', 'Left', ...
            'String', '2', ...
            'TooltipString', 'Output file', ...
            'Units','normalized',...
            'Callback', {@columnsCtrlCallback}, ...
            'Position', [0.15 0.35 0.6 0.1]);
    end % createEditBoxes

    function createLabels(panel)
        % Creates the labels in the panel
        uicontrol('parent', panel, ...
            'Style', 'Text', ...
            'FontWeight', 'bold', ...
            'Units', 'normalized', ...
            'String', 'Remap HED tags', ...
            'HorizontalAlignment', 'Left', ...
            'Position', [0 0.9 0.4 0.1]);
        uicontrol('parent', panel, ...
            'Style', 'Text', ...
            'Units', 'normalized', ...
            'String', ['Replaces the tags in a tab-delimited input' ...
            ' file based on a remap file. Press the help button' ...
            ' for instructions.'], ...
            'HorizontalAlignment', 'Left', ...
            'Position', [0 0.865 1 0.1]);
        uicontrol('parent', panel, ...
            'Style', 'Text', ...
            'Units', 'normalized', ...
            'String', 'Input file', ...
            'HorizontalAlignment', 'Left', ...
            'Position', [0 0.8 0.12 0.08]);
        uicontrol('parent', panel, ...
            'Style', 'Text', ...
            'Units', 'normalized', ...
            'String', 'Remap file', ...
            'HorizontalAlignment', 'Left', ...
            'Position', [0 0.65 0.12 0.08]);
        uicontrol('parent', panel, ...
            'Style', 'Text', ...
            'Units', 'normalized', ...
            'String', 'Output File', ...
            'HorizontalAlignment', 'Left', ...
            'Position', [0 0.5 0.12 0.08]);
        uicontrol('parent', panel, ...
            'Style', 'Text', ...
            'Units', 'normalized', ...
            'String', 'Input file tag columns', ...
            'HorizontalAlignment', 'Left', ...
            'Position', [0 0.35 0.12 0.08]);
    end % createLabels

    function createPanel(tab)
        % Creates replace tags layout
        panel = uipanel('Parent', tab, ...
            'BorderType', 'none', ...
            'BackgroundColor', [.94 .94 .94], ...
            'FontSize', 12, ...
            'Position', [0 0 1 1]);
        createLabels(panel);
        createEditBoxes(panel);
        createButtons(panel);
    end % createPanel


    function outputCtrlCallback(src, eventdata) %#ok<INUSD>
        % Callback for user directly editing the 'Output' editbox
        outputFile = get(src, 'String');
    end % outputCtrlCallback

    function replaceCallback(src, eventdata) %#ok<INUSD>
        % Callback for the tag validation button
        % Callback for convert button
        if isempty(mapFile)
            errordlg('Map file is empty');
        elseif isempty(tsvFile)
            errordlg('Tab-delimited file is empty');
        elseif isempty(outputFile)
            errordlg('Output is empty');
        elseif isempty(tsvTagColumns)
            errordlg('Columns are empty');
        else
            wb = waitbar(.5,'Please wait...');
            try
                remapTSVTags(mapFile, tsvFile, tsvTagColumns, ...
                    'OutputFile', outputFile);
                msgbox('Tag update complete');
            catch
                errordlg('Tag update failed');
            end
            close(wb);
        end
    end % replaceCallback

    function helpCallback(src, eventdata) %#ok<INUSD>
        % Callback for the 'Validate' button
        helpdlg(['Updates the tags in a tab-delimited text' ...
            ' file based on a map file. The map file is used' ...
            ' to replace the invalid older schema tags with' ...
            ' valid new schema tags. The HED' ...
            ' map file consists of two tab-delimited columns: the' ...
            ' first column containing tags from the older HED schema' ...
            ' and the second column containing the replacement tags' ...
            ' from the newer HED schema. The ''Output File'' is the' ...
            ' ''Tab-Delimited File'' with the tags replaced from the' ...
            ' HED map file. with the is The columns are to be' ...
            ' specified with a single number or a comma separated list' ...
            ' of numbers'], 'Tag Update Instructions');
    end % helpCallback

    function mapCtrlCallback(src, eventdata) %#ok<INUSD>
        % Callback for user directly editing the 'Remap' editbox
        mapFile = get(src, 'String');
    end % mapCtrlCallback

    function setOutput(dName)
        % Sets the 'Output' edit box based on the 'Tags' editbox
        if isempty(tsvFile)
            outputFile = fullfile(dName, ...
                [latestHED '_replace.txt']);
        else
            [~, file] = fileparts(tsvFile);
            outputFile = fullfile(dName, [file '_replace.txt']);
        end
        set(outputCtrl, 'String', outputFile);
    end % setOutput

    function tsvCtrlCallback(src, eventdata) %#ok<INUSD>
        % Callback for user directly editing the 'Tags' editbox
        tsvFile = get(src, 'String');
    end % tsvCtrlCallback

end % createRemapTagsLayout