function [okay, success] = createUpdateAvailableLayout(version)
title = 'Update Available';
okay = false;
success = false;
fig = createFigure(title);
createPanel1();
createPanel2();
movegui(fig);
uiwait(fig);

    function createButtons(panel)
        % Creates the buttons in the panel
        uicontrol('Parent', panel, ...
            'String', 'OK', ...
            'Style', 'pushbutton', ...
            'TooltipString', ...
            'Presse to validate HED event tags', ...
            'Units','normalized',...
            'Callback', {@okCallback}, ...
            'Position', [0.575 0.1 0.2 0.35]);
        uicontrol('Parent', panel, ...
            'String', 'Skip', ...
            'Style', 'pushbutton', ...
            'TooltipString', ...
            'Presse to validate HED event tags', ...
            'Units','normalized',...
            'Callback', {@skipCallback}, ...
            'Position', [0.79 0.1 0.2 0.35]);
    end % createButtons

    function fig = createFigure(title)
        % Creates a figure and sets the properties
        fig = figure( ...
            'Color', [.94 .94 .94], ...
            'MenuBar', 'none', ...
            'Name', title, ...
            'NextPlot', 'add', ...
            'NumberTitle','off', ...
            'Position', [750, 750, 500, 200], ...
            'Resize', 'on', ...
            'Tag', title, ...
            'Toolbar', 'none', ...
            'Visible', 'on');
    end % createFigure

    function createPanel1()
        % Creates the tab panel
        panel = uipanel('Parent', fig, ...
            'BackgroundColor', [.94 .94 .94], ...
            'FontSize', 12, ...
            'Position', [0 .5 1 .5]);
        createLabels1(panel);
    end % createPanel1

    function createPanel2()
        % Creates the tab panel
        panel = uipanel('Parent', fig, ...
            'BackgroundColor', [.94 .94 .94], ...
            'FontSize', 12, ...
            'Position', [0 0 1 .5]);
        createLabels2(panel);
        createButtons(panel);
    end % createPanel1

    function createLabels1(panel)
        uicontrol('parent', panel, ...
            'Style', 'Text', ...
            'Units', 'normalized', ...
            'String', ['A new version of the HED XML schema is' ...
            ' available. Do you want to download it now?'], ...
            'HorizontalAlignment', 'Left', ...
            'Position', [0.1 0.55 0.8 0.4]);
    end

    function createLabels2(panel)
        uicontrol('parent', panel, ...
            'Style', 'Text', ...
            'Units', 'normalized', ...
            'String', ['Version: ' version], ...
            'HorizontalAlignment', 'Left', ...
            'Position', [0.1 0.75 0.8 0.2]);
        url = 'https://github.com/BigEEGConsortium/HED/wiki/HED-Schema';
        labelStr = ['<html>From: <a href="">' url ...
            '</a></html>'];
        jLabel = javaObjectEDT('javax.swing.JLabel', labelStr);
        [hjLabel,hContainer] = javacomponent(jLabel, [10,10,250,20], ...
            panel);
        set(hContainer, 'Units','norm');
        set(hContainer, 'Position', [0.1 .45 1 0.35]);
        % Modify the mouse cursor when hovering on the label
        hjLabel.setCursor(java.awt.Cursor.getPredefinedCursor(...
            java.awt.Cursor.HAND_CURSOR));
        % Set the label's tooltip
        hjLabel.setToolTipText(['Visit the ' url ' website']);
        % Set the mouse-click callback
        set(hjLabel, 'MouseClickedCallback', @(h,e)web(url, '-browser'));
    end

    function okCallback(src, evnt) %#ok<INUSD>
        wb = waitbar(.5,'Updating...');
        try         
            replaceHED();
            close(wb);
            success = true;
            msgbox('Update complete', 'Success','modal');
        catch
            close(wb);
            success = false;
            msgbox('Update failed', 'Failure','modal');
        end
        okay = true;
        close(fig);
    end % okCallback

    function skipCallback(src, evnt) %#ok<INUSD>
        close(fig);
    end % skipCallback

end