function replacetsv_input(tab)
latestHED = 'HED 2.026';
mapFile = '';
tsvFile = '';
outputFile = '';
tsvTagColumns = '2';
mapCtrl = '';
tsvCtrl = '';
outputCtrl = '';
createPanel(tab);

    function browseOutputCallback(src, eventdata, replaceOutputCtrl, ...
            myTitle) %#ok<INUSL>
        % Callback for browse button sets a directory for control      
        defaultName = '';
        if ~isempty(tsvFile)
           [~, defaultName, ext] = fileparts(tsvFile); 
           defaultName = [defaultName '_update' ext];
        end
        [file, path] = uiputfile({'*.tsv', 'Tab-separated files(*.tsv)'}, ...
            myTitle, defaultName);
        if ischar(file) && ~isempty(file)
            outputFile = fullfile(path, file);
            set(replaceOutputCtrl, 'String', outputFile);
        end
    end % browseOutputCallback

    function browseMapCallback(src, eventdata, replaceTxtCtrl, ...
            myTitle) %#ok<INUSL>
        % Callback for 'Browse' button that sets the 'replacement' editbox
        [tFile, tPath] = uigetfile({'*.tsv', 'Tab-separated files'; ...
            '*.txt', 'Text files'; '*.*', 'All files'}, myTitle);
        if tFile ~= 0
            mapFile = fullfile(tPath, tFile);
            set(replaceTxtCtrl, 'String', mapFile);
        end
    end % browseMapCallback

    function browseTagsCallback(src, eventdata, replaceTagCtrl, ...
            myTitle) %#ok<INUSL>
        % Callback for 'Browse' button that sets the 'Tags' editbox
        [tFile, tPath] = uigetfile({'*.tsv', 'Tab-separated files'; ...
            '*.txt', 'Text files'; '*.*', 'All files'}, myTitle);
        if tFile ~= 0
            tsvFile = fullfile(tPath, tFile);
            set(replaceTagCtrl, 'String', tsvFile);
        end
    end % browseTagsCallback

    function columnsCtrlCallback(src, eventdata) %#ok<INUSD>
        % Callback for user directly editing the 'Columns' editbox
        tsvTagColumns = str2num(get(src, 'String')); %#ok<ST2NM>
    end % columnsCtrlCallback

    function createButtons(panel)
        % Creates the buttons in the panel
        uicontrol('Parent', panel, ...
            'String', 'Browse', ...
            'Style', 'pushbutton', ...
            'TooltipString', ['Press to choose tab-separated input' ...
            ' file.'], ...
            'Units','normalized',...
            'Callback', {@browseTagsCallback, ...
            tsvCtrl, ...
            'Browse for HED replacement file'}, ...
            'Position', [0.775 0.9 0.2 0.1]);
        uicontrol('Parent', panel, ...
            'String', 'Browse', ...
            'Style', 'pushbutton', ...
            'TooltipString', 'Press to choose replacement file.', ...
            'Units','normalized',...
            'Callback', {@browseMapCallback, ...
            mapCtrl, 'Browse for tag file'}, ...
            'Position', [0.775 0.75 0.2 0.1]);
        uicontrol('Parent', panel, ...
            'String', 'Browse', ...
            'Style', 'pushbutton', ...
            'TooltipString', ...
            'Press to choose output file.', ...
            'Units','normalized',...
            'Callback', {@browseOutputCallback, ...
            outputCtrl, ...
            'Browse for output file'}, ...
            'Position', [0.775 0.6 0.2 0.1]);
        uicontrol('Parent', panel, ...
            'String', 'Help', ...
            'Style', 'pushbutton', ...
            'TooltipString', ...
            'Press for instructions.', ...
            'Units','normalized',...
            'Callback', {@helpCallback}, ...
            'Position', [0.775 .45 0.2 0.1]);
        uicontrol('Parent', panel, ...
            'String', 'Update', ...
            'Style', 'pushbutton', ...
            'TooltipString', 'Press when finished', ...
            'Units','normalized',...
            'Callback', {@replaceCallback}, ...
            'Position', [0.775 0.025 0.2 0.1]);
    end % createButtons

    function createEditBoxes(panel)
        % Creates the edit boxes in the panel
        tsvCtrl = uicontrol('Parent', panel, ...
            'Style', 'edit', ...
            'BackgroundColor', 'w', ...
            'HorizontalAlignment', 'Left', ...
            'String', '', ...
            'TooltipString', ['A tab-separated input file containing' ...
            ' HED tags.'], ...
            'Units','normalized',...
            'Callback', {@tsvCtrlCallback}, ...
            'Position', [0.15 0.9 0.6 0.1]);
        mapCtrl = uicontrol('Parent', panel, ...
            'Style', 'edit', ...
            'BackgroundColor', 'w', ...
            'HorizontalAlignment', 'Left', ...
            'Tag', 'validateHedXmlEdit', ...
            'String', '', ...
            'TooltipString', ['A tab-separated replacement file containing' ...
            ' tags that generated issues from a previous validation.' ...
            ' Any tags not in this file that generate issues will be' ...
            ' appended to first column.'], ...
            'Units','normalized',...
            'Callback', {@mapCtrlCallback}, ...
            'Position', [0.15 0.75 0.6 0.1]);
        outputCtrl = uicontrol('Parent', panel, ...
            'Style', 'edit', ...
            'BackgroundColor', 'w', ...
            'HorizontalAlignment', 'Left', ...
            'String', '', ...
            'TooltipString', ['A tab-separated output file containing' ...
            ' the updated HED tags.'], ...
            'Units','normalized',...
            'Callback', {@outputCtrlCallback}, ...
            'Position', [0.15 0.6 0.6 0.1]);
        uicontrol('Parent', panel, ...
            'Style', 'edit', ...
            'BackgroundColor', 'w', ...
            'HorizontalAlignment', 'Left', ...
            'String', '2', ...
            'TooltipString', 'Output file', ...
            'Units','normalized',...
            'Callback', {@columnsCtrlCallback}, ...
            'Position', [0.15 0.45 0.6 0.1]);
    end % createEditBoxes

    function createLabels(panel)
        % Creates the labels in the panel
        uicontrol('parent', panel, ...
            'Style', 'Text', ...
            'Units', 'normalized', ...
            'String', 'TSV input file', ...
            'HorizontalAlignment', 'Left', ...
            'Position', [0 0.9 0.13 0.08]);
        uicontrol('parent', panel, ...
            'Style', 'Text', ...
            'Units', 'normalized', ...
            'String', 'Replace file', ...
            'HorizontalAlignment', 'Left', ...
            'Position', [0 0.75 0.12 0.08]);
        uicontrol('parent', panel, ...
            'Style', 'Text', ...
            'Units', 'normalized', ...
            'String', 'Output file', ...
            'HorizontalAlignment', 'Left', ...
            'Position', [0 0.6 0.12 0.08]);
        uicontrol('parent', panel, ...
            'Style', 'Text', ...
            'Units', 'normalized', ...
            'String', 'HED tag columns', ...
            'HorizontalAlignment', 'Left', ...
            'Position', [0 0.45 0.12 0.08]);
    end % createLabels

    function createPanel(tab)
        % Creates replace tags layout
        panel = uipanel('Parent', tab, ...
            'BorderType', 'none', ...
            'BackgroundColor', [.94 .94 .94], ...
            'FontSize', 12, ...
            'Position', [0 0 1 1]);
        createLabels(panel);
        createEditBoxes(panel);
        createButtons(panel);
    end % createPanel


    function outputCtrlCallback(src, eventdata) %#ok<INUSD>
        % Callback for user directly editing the 'Output' editbox
        outputFile = get(src, 'String');
    end % outputCtrlCallback

    function replaceCallback(src, eventdata) %#ok<INUSD>
        % Callback for the tag validation button
        % Callback for convert button
        if isempty(mapFile)
            errordlg('Replace file is empty');
        elseif isempty(tsvFile)
            errordlg('Tab-separated file is empty');
        elseif isempty(outputFile)
            errordlg('Output file is empty');
        elseif isempty(tsvTagColumns)
            errordlg('HED tag columns are empty');
        else
            wb = waitbar(.5,'Please wait...');
            try
                remapTSVTags(mapFile, tsvFile, tsvTagColumns, ...
                    'OutputFile', outputFile);
                msgbox('Complete!');
            catch
                errordlg('Failed!');
            end
            close(wb);
        end
    end % replaceCallback

    function helpCallback(src, eventdata) %#ok<INUSD>
        % Callback for the 'Validate' button
        helpdlg(sprintf(['Find and replace the HED tags in a' ...
            ' tab-separated file.\n\n**Options*** \n\nTSV input file' ...
            ' - A tab-separated file containing HED tags in a single' ...
            ' column or multiple columns. \n\nReplace file - A two' ...
            ' column tab-separated file used to find and replace the' ...
            ' HED tags in the input file. The first column will be the' ...
            ' HED tags to find and the second column will be HED tags' ...
            ' that will replace them.\n\nOutput file - A tab-separated' ...
            ' file that is the result of the find and replace' ...
            ' performed on the input file.\n\nHED tag columns - The' ...
            ' columns in the tab-separated input file that contains' ...
            ' the HED tags. This is to be specified with a single' ...
            ' number or a comma separated list of numbers (e.g. 1' ...
            ' or 1,2,3,4). The default will be the second column.']), ...
            'Instructions');
    end % helpCallback

    function mapCtrlCallback(src, eventdata) %#ok<INUSD>
        % Callback for user directly editing the 'replacement' editbox
        mapFile = get(src, 'String');
    end % mapCtrlCallback

    function tsvCtrlCallback(src, eventdata) %#ok<INUSD>
        % Callback for user directly editing the 'Tags' editbox
        tsvFile = get(src, 'String');
    end % tsvCtrlCallback

end % replacetsv_input