function updatehed_input(tab)
versionCtrl = '';
currentVersion = getXMLHEDVersion('HED.xml');
createPanel(tab);

    function createButtons(panel)
        % Creates the buttons in the panel
        uicontrol('Parent', panel, ...
            'String', 'Check', ...
            'Style', 'pushbutton', ...
            'TooltipString', 'Press to choose check for latest version', ...
            'Units','normalized',...
            'Callback', {@updateCallback}, ...
            'Position', [0.775 0.025 0.2 0.1]);
    end % createButtons

    function createLabels(panel)
        % Creates the labels in the panel
        uicontrol('parent', panel, ...
            'Style', 'Text', ...
            'Units', 'normalized', ...
            'String', 'Check for a newer HED version', ...
            'HorizontalAlignment', 'Left', ...
            'Position', [0 0.8 0.5 0.2]);
        versionCtrl = uicontrol('parent', panel, ...
            'Style', 'Text', ...
            'Units', 'normalized', ...
            'String', ['Current HED version: ' currentVersion], ...
            'HorizontalAlignment', 'Left', ...
            'Position', [0 0 0.5 0.05]);
        
    end % createLabels

    function createPanel(tab)
        % Creates HED mapping layout
        panel = uipanel('Parent', tab, ...
            'BorderType', 'none', ...
            'BackgroundColor', [.94 .94 .94], ...
            'FontSize', 12, ...
            'Position', [0 0 1 1]);
        createLabels(panel);
        createButtons(panel);
    end % createPanel

    function updateCallback(src, evnt) %#ok<INUSD>
        latestVersion = downloadHED();
        if ~strcmp(currentVersion, latestVersion)
            [okay, success] = availablehed_input(latestVersion);
            if okay && success
                currentVersion = latestVersion;
                set(versionCtrl, 'String', ...
                    ['Current HED version: ' currentVersion]);
            end
        else
            msgbox('The current version is up to date');
        end
    end % updateCallback

end % updatehed_input