% tagstudy_input
% GUI for input needed to create inputs for validatestudy
%
% Usage:
%   >>  validatestudy_input()
%
% Description:
% validatestudy_input() brings up a GUI for input needed to create inputs
% for validatestudy
%
% Function documentation:
% Execute the following in the MATLAB command window to view the function
% documentation for tagstudy_input:
%
%    doc tagstudy_input
% See also: valideatestudy, pop_validatestudy
%
% Copyright (C) Kay Robbins and Jeremy Cockfield, UTSA, 2011-2013,
% krobbins@cs.utsa.edu
%
% This program is free software; you can redistribute it and/or modify
% it under the terms of the GNU General Public License as published by
% the Free Software Foundation; either version 2 of the License, or
% (at your option) any later version.
%
% This program is distributed in the hope that it will be useful,
% but WITHOUT ANY WARRANTY; without even the implied warranty of
% MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
% GNU General Public License for more details.
%
% You should have received a copy of the GNU General Public License
% along with this program; if not, write to the Free Software
% Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA

function [cancelled, extensionsAllowed, hedXML, outputDir, datasetFile, ...
    validateDatasets] = validateeeg_input()
% Setup the variables used by the GUI
cancelled = true;
extensionsAllowed = true;
hedXML = which('HED.xml');
outputDir = pwd;
datasetFile = '';
validateDatasets = false;
title = 'Inputs for validating EEG dataset HED tags';
fig = createFigure(title);
addFigureComponents(fig);
movegui(fig);
uiwait(fig);

    function addBrowserComponents(browserPanel)
        % Adds components to the browser panel
        addBrowserLabels(browserPanel);
        addBrowserEditBoxes(browserPanel);
        addBrowserButtons(browserPanel);
    end % addBrowserComponents

    function addBrowserButtons(browserPanel)
        % Adds button components to the browser panel
        uicontrol('Parent', browserPanel, ...
            'string', 'Browse', ...
            'style', 'pushbutton', ...
            'TooltipString', 'Press to bring up file chooser chooser', ...
            'Units','normalized',...
            'Callback', @browseStudyButtonCallback, ...
            'Position', [0.775 .8 0.21 0.2]);
        uicontrol('Parent', browserPanel, ...
            'string', 'Browse', ...
            'style', 'pushbutton', ...
            'TooltipString', 'Press to bring up file chooser chooser', ...
            'Units', 'normalized',...
            'Callback', {@browseHedXMLCallback, ...
            'Browse for HED XML file'}, ...
            'Position', [0.775 .5 0.21 0.2]);
        uicontrol('Parent', browserPanel, ...
            'string', 'Browse', ...
            'style', 'pushbutton', ...
            'TooltipString', 'Press to bring up file chooser chooser', ...
            'Units', 'normalized',...
            'Callback', {@browseOutputDirectoryCallback, ...
            'Browse for ouput directory'}, ...
            'Position', [0.775 .2 0.21 0.2]);
    end % addBrowserButtons

    function addBrowserEditBoxes(browserPanel)
        % Adds edit box components to the browser panel
        uicontrol('Parent', browserPanel, ...
            'Style', 'edit', ...
            'BackgroundColor', 'w', ...
            'HorizontalAlignment', 'Left', ...
            'Tag', 'datasetEB', ...
            'String', '', ...
            'TooltipString', 'EEG dataset file name', ...
            'Units','normalized',...
            'Callback', @datasetEditBoxCallback, ...
            'Position', [0.15 0.8 0.6 0.2]);
        uicontrol('Parent', browserPanel, ...
            'Style', 'edit', ...
            'BackgroundColor', 'w', ...
            'HorizontalAlignment', 'Left', ...
            'Tag', 'HEDXMLEB', ...
            'String', hedXML, ...
            'TooltipString', ['A directory where the validation output' ...
            ' is written to if the ''Write Output'' checkbox' ...
            ' is checked.'], ...
            'Units','normalized',...
            'Callback', {@hedEditBoxCallback}, ...
            'Position', [0.15 0.5 0.6 0.2]);
        uicontrol('Parent', browserPanel, ...
            'Style', 'edit', ...
            'BackgroundColor', 'w', ...
            'HorizontalAlignment', 'Left', ...
            'Tag', 'OutputDirEB', ...
            'String', outputDir, ...
            'TooltipString', ['A directory where the validation output' ...
            ' is written to if the ''Write Output'' checkbox' ...
            ' is checked.'], ...
            'Units','normalized',...
            'Callback', {@outputDirEditBoxCallback}, ...
            'Position', [0.15 0.2 0.6 0.2]);
    end % addBrowserEditBoxes

    function addBrowserLabels(browserPanel)
        % Adds label components to the browser panel
        uicontrol('Parent', browserPanel, ...
            'Style','text', ...
            'String', 'Study file', ...
            'Units','normalized',...
            'HorizontalAlignment', 'Left', ...
            'Position', [0.015 0.75 0.1 0.2]);
        uicontrol('Parent', browserPanel, ...
            'Style','text', ...
            'String', 'HED file', ...
            'Units','normalized',...
            'HorizontalAlignment', 'Left', ...
            'Position', [0.015 0.35 0.12 0.3]);
        uicontrol('parent', browserPanel, ...
            'Style', 'Text', ...
            'Units', 'normalized', ...
            'String', 'Output directory', ...
            'HorizontalAlignment', 'Left', ...
            'Position', [0.015 0.2 0.12 0.2]);
    end % addBrowserLabels

    function addDescriptionComponents(descriptionPanel)
        % Adds components to the description panel
        uicontrol('parent', descriptionPanel, ...
            'Style', 'Text', ...
            'FontWeight', 'bold', ...
            'Units', 'normalized', ...
            'String', 'Validate study tags', ...
            'HorizontalAlignment', 'Left', ...
            'Position', [0 0.8 0.4 0.2]);
        uicontrol('parent', descriptionPanel, ...
            'Style', 'Text', ...
            'Units', 'normalized', ...
            'String', ['Validates the HED tags in a EEG study and the' ...
            ' datasets that are associated with it. Please specify a' ...
            ' study file that you want to be validated. There will be' ...
            ' a output file generated for the study file and each' ...
            ' dataset that is validated. By default only the HED tags' ...
            ' in the study file are validated. Check the' ...
            ' ''Validate study dataset files'' checkbox to validate' ...
            ' the datasets also.'], ...
            'HorizontalAlignment', 'Left', ...
            'Position', [0 0.1 1 0.7]);
    end % addDescriptionComponents

    function addFigureComponents(fig)
        % Adds components to the figure
        [descriptionPanel, browserPanel, optionPanel, sumissionPanel] = ...
            createPanels(fig);
        addDescriptionComponents(descriptionPanel);
        addBrowserComponents(browserPanel);
        addOptionComponents(optionPanel);
        addSubmissionComponents(fig, sumissionPanel);
    end % addFigureComponents

    function addOptionComponents(optionPanel)
        % Adds components to the option panel
        uicontrol('Parent', optionPanel, ...
            'Style', 'CheckBox', ...
            'Tag', 'ValidateAllCB', ...
            'String', 'Validate study dataset files', ...
            'Enable', 'on', ...
            'Tooltip', ['If checked, save tags to study datasets in' ...
            ' addition to study file'], ...
            'Value', 0, ...
            'Units','normalized', ...
            'Callback', @validateAllCallback, ...
            'Position', [0.1 0.6 0.8 0.3]);
        uicontrol('Parent', optionPanel, ...
            'Style', 'CheckBox', ...
            'String', 'Extensions allowed', ...
            'Enable', 'on', ...
            'Tooltip', ['If checked, save tags to study datasets in' ...
            ' addition to study file'], ...
            'Value', 1, ...
            'Units','normalized', ...
            'Callback', @extensionsAllowedCallback, ...
            'Position', [0.1 0.2 0.8 0.3]);
    end % addOptionComponents

    function addSubmissionComponents(fig, submissionPanel)
        % Adds components to the submission panel
        uicontrol('Parent', submissionPanel, ...
            'Style', 'pushbutton', ...
            'String', 'Okay', ...
            'Enable', 'on', ...
            'Tooltip', 'Save the current configuration in a file', ...
            'Units','normalized', ...
            'Callback', {@okayButtonCallback, fig}, ...
            'Position',[0.025 0.3 0.45 0.4]);
        uicontrol('Parent', submissionPanel, ...
            'Style', 'pushbutton', 'Tag', 'CancelButton', ...
            'String', 'Cancel', 'Enable', 'on', 'Tooltip', ...
            'Cancel the directory tagging', ...
            'Units','normalized', ...
            'Callback', {@cancelButtonCallback, fig}, ...
            'Position',[0.515 0.3 0.45 0.4]);
    end % addSubmissionComponents

    function [descriptionPanel, browserPanel, optionPanel, ...
            sumissionPanel] = createPanels(fig)
        % Creates the panels in the figure
        descriptionPanel = uipanel(fig, ...
            'BorderType','none', ...
            'BackgroundColor',[.94 .94 .94],...
            'FontSize', 12,...
            'Position',[0 .8 1 .2]);
        browserPanel = uipanel(fig, ...
            'BorderType','none', ...
            'BackgroundColor',[.94 .94 .94],...
            'FontSize', 12,...
            'Position',[0 .4 1 .4]);
        optionPanel = uipanel(fig, ...
            'BackgroundColor',[.94,.94,.94],...
            'FontSize', 12,...
            'Title','Additional options', ...
            'Position',[0.15 0.2 0.6 0.2]);
        sumissionPanel = uipanel(fig, ...
            'BorderType','none', ...
            'BackgroundColor',[.94 .94 .94],...
            'FontSize', 12,...
            'Position', [0.6 0 .4 .2]);
    end % createPanels

    function browseHedXMLCallback(src, eventdata, myTitle) %#ok<INUSL>
        % Callback for 'Browse' button that sets the 'HED' editbox
        [tFile, tPath] = uigetfile({'*.xml', 'XML files (*.xml)'}, ...
            myTitle);
        if tFile ~= 0
            hedXML = fullfile(tPath, tFile);
            set(findobj('Tag', 'HEDXMLEB'), 'String', hedXML);
        end
    end % browseHedXMLCallback

    function browseOutputDirectoryCallback(~, ~, myTitle) 
        % Callback for browse button to set the output directory editbox
        startPath = get(findobj('Tag', 'OutputDirEB'), 'String');
        if isempty(startPath) || ~ischar(startPath) || ~isdir(startPath)
            startPath = pwd;
        end
        dName = uigetdir(startPath, myTitle);
        if dName ~=0
            set(findobj('Tag', 'OutputDirEB'), 'String', dName);
            outputDir = dName;
        end
    end % browseOutputDirectoryCallback

    function browseStudyButtonCallback(~, ~)
        % Callback for browse button to set study file in edit box
        [file, filePath] = uigetfile({'*.study', ...
            'Study files(*.study)'}, 'Browse for study file');
        study = fullfile(filePath, file);
        if ischar(study) && ~isempty(study)
            set(findobj('Tag', 'StudyEB'), 'String', study);
            datasetFile = study;
        end
    end % browseStudyButtonCallback

    function cancelButtonCallback(~, ~, fig)  
        % Callback for the cancel button
        cancelled = true;
        close(fig);
    end % cancelButtonCallback

    function fig = createFigure(title)
        % Creates the figure with the given title
        fig = figure( ...
            'Color', [.94 .94 .94], ...
            'MenuBar', 'none', ...
            'Name', title, ...
            'NextPlot', 'add', ...
            'NumberTitle','off', ...
            'Resize', 'on', ...
            'Tag', title, ...
            'Toolbar', 'none', ...
            'Visible', 'off', ...
            'WindowStyle', 'modal');
    end % createFigure

    function extensionsAllowedCallback(src, ~) 
        % Callback for extensions allowed checkbox
        extensionsAllowed = get(src, 'Max') == get(src, 'Value');
    end % extensionAllowedCallback

    function hedEditBoxCallback(src, ~) 
        % Callback for user directly editing the HED XML editbox
        xml = get(src, 'String');
        if exist(xml, 'file')
            hedXML = xml;
        else 
            errordlg(['XML file is invalid. Setting the XML' ...
                ' file back to the previous file.'], ...
                'Invalid XML file');
            set(src, 'String', hedXML);
        end
    end % hedEditBoxCallback

    function okayButtonCallback(~, ~, fig)
        % Callback for the okay button
        cancelled = false;
        close(fig);
    end % okayButtonCallback

    function outputDirEditBoxCallback(src, ~)
        % Callback for user directly editing the output directory edit box
        directory = get(src, 'String');
        if exist(directory, 'dir')
            outputDir = directory;
        else 
            errordlg(['Output directory is invalid. Setting the output' ...
                ' directory back to the previous directory.'], ...
                'Invalid output directory');
            set(src, 'String', outputDir);
        end
    end % outputDirEditBoxCallback

    function datasetEditBoxCallback(src, ~)
        % Callback for user directly editing the study edit box
        dataset = get(src, 'String');
        if exist(dataset, 'file')
            datasetFile = dataset;
        else
            errordlg(['Dataset file is invalid. Setting the dataset' ...
                ' file back to the previous dataset file.'], ...
                'Invalid dataset file');
            set(src, 'String', datasetFile);
        end
    end % datasetEditBoxCallback

end % tagstudy_input