function validatetsv_input(tab)
latestHED = 'HED.xml';
hedXMLPath = which(latestHED);
hedXML = hedXMLPath;
remapFile = '';
tsvFile = '';
outDir = pwd;
tsvTagColumns = 2;
hasHeader = true;
generateWarnings = false;
hedXMLCtrl = '';
tsvFileCtrl = '';
remapFileCtrl = '';
outputDirectoryCtrl = '';
createPanel(tab);

    function browseHedXMLCallback(src, eventdata, hedCtrl, ...
            myTitle) %#ok<INUSL>
        % Callback for 'Browse' button that sets the 'HED' editbox
        [tFile, tPath] = uigetfile({'*.xml', 'XML files (*.xml)'}, ...
            myTitle);
        if tFile ~= 0
            hedXML = fullfile(tPath, tFile);
            set(hedCtrl, 'String', hedXML);
        end
    end % browseHedXMLCallback

    function browseOutputDirectoryCallback(src, eventdata, ...
            outputTxtCtrl, myTitle) %#ok<INUSL>
        % Callback for 'Browse' button that sets the 'Output' editbox
        startPath = get(outputTxtCtrl, 'String');
        if isempty(startPath) || ~ischar(startPath) || ~isdir(startPath)
            startPath = pwd;
        end
        dName = uigetdir(startPath, myTitle);
        if dName ~=0
            setOutputDirectory(dName);
        end
    end % browseOutputDirectoryCallback

    function browseTSVFileCallback(src, eventdata, tagsCtrl, ...
            myTitle) %#ok<INUSL>
        % Callback for 'Browse' button that sets the 'Tags' editbox
        [tFile, tPath] = uigetfile({'*.tsv', 'Tab-separated files'; ...
            '*.txt', 'Text files'; '*.*', 'All files'}, myTitle);
        if tFile ~= 0
            tsvFile = fullfile(tPath, tFile);
            set(tagsCtrl, 'String', tsvFile);
        end
    end % browseTSVFileCallback

    function browseReMapFileCallback(src, eventdata, remapCtrl, ...
            myTitle) %#ok<INUSL>
        % Callback for 'Browse' button that sets the 'Tags' editbox
        [tFile, tPath] = uigetfile({'*.tsv', 'Tab-separated files'; ...
            '*.txt', 'Text files'; '*.*', 'All files'}, myTitle);
        if tFile ~= 0
            remapFile = fullfile(tPath, tFile);
            set(remapCtrl, 'String', remapFile);
        end
    end % browseReMapFileCallback

    function createButtons(panel)
        % Creates the buttons in the panel
        uicontrol('Parent', panel, ...
            'String', 'Browse', ...
            'Style', 'pushbutton', ...
            'TooltipString', 'Press to choose a HED schema', ...
            'Units','normalized',...
            'Callback', {@browseHedXMLCallback, ...
            hedXMLCtrl, 'Browse for HED XML file'}, ...
            'Position', [0.775 0.9 0.2 0.1]);
        uicontrol('Parent', panel, ...
            'String', 'Browse', ...
            'Style', 'pushbutton', ...
            'TooltipString', 'Press to choose a tab-separated file', ...
            'Units','normalized',...
            'Callback', {@browseTSVFileCallback, ...
            tsvFileCtrl, 'Browse for tab-separated file'}, ...
            'Position', [0.775 0.75 0.2 0.1]);
        uicontrol('Parent', panel, ...
            'String', 'Browse', ...
            'Style', 'pushbutton', ...
            'TooltipString', ...
            'Press to choose a replacement file', ...
            'Units','normalized',...
            'Callback', {@browseReMapFileCallback, ...
            remapFileCtrl, ...
            'Browse for map file'}, ...
            'Position', [0.775 0.6 0.2 0.1]);
        uicontrol('Parent', panel, ...
            'String', 'Browse', ...
            'Style', 'pushbutton', ...
            'TooltipString', ...
            'Press to choose a output directory', ...
            'Units','normalized',...
            'Callback', {@browseOutputDirectoryCallback, ...
            outputDirectoryCtrl, ...
            'Browse for ouput directory'}, ...
            'Position', [0.775 0.45 0.2 0.1]);
        uicontrol('Parent', panel, ...
            'String', 'Help', ...
            'Style', 'pushbutton', ...
            'TooltipString', ...
            'Press for instructions.', ...
            'Units','normalized',...
            'Callback', {@helpCallback}, ...
            'Position', [0.775 0.3 0.2 0.1]);
        uicontrol('Parent', panel, ...
            'String', 'Validate', ...
            'Style', 'pushbutton', ...
            'TooltipString', ...
            'Press when finished', ...
            'Units','normalized',...
            'Callback', {@validateTSVTagsCallback}, ...
            'Position', [0.775 0.025 0.2 0.1]);
    end % createButtons

    function createCheckboxes()
        % Creates the checkboxes in the panel
        panel = uipanel('Parent', tab, ...
            'BackgroundColor', [.94 .94 .94], ...
            'FontSize', 12, ...
            'Position', [0.15 0.02 0.6 0.2], ...
            'Title', 'Additional options');
        uicontrol('Parent', panel, ...
            'Style', 'checkbox', ...
            'HorizontalAlignment', 'Left', ...
            'String', 'Tab-separated input file has a header', ...
            'Value', hasHeader, ...
            'TooltipString', ['Check if the tab-separated input file' ...
            ' has a header, uncheck if it does not have a header.'], ...
            'Units','normalized',...
            'Callback', {@hasHeaderCallback}, ...
            'Position', [0.04 0.6 0.7 0.4]);
        uicontrol('Parent', panel, ...
            'Style', 'checkbox', ...
            'HorizontalAlignment', 'Left', ...
            'String', 'Include warnings in log file', ...
            'Value', generateWarnings, ...
            'TooltipString', ['Check if the validation output is' ...
            ' written to the workspace and a set of files in' ...
            ' the same directory, uncheck if the validation ouput is' ...
            ' only written to the workspace.'], ...
            'Units','normalized',...
            'Callback', {@errorLogCallback}, ...
            'Position', [0.04 0.1 0.7 0.4]);
    end % createCheckboxes

    function createEditBoxes(panel)
        % Creates the edit boxes in the panel
        hedXMLCtrl = uicontrol('Parent', panel, ...
            'Style', 'edit', ...
            'BackgroundColor', 'w', ...
            'HorizontalAlignment', 'Left', ...
            'String', hedXMLPath, ...
            'TooltipString', 'A HED XML file used for validation.', ...
            'Units','normalized',...
            'Callback', {@hedCtrlCallback}, ...
            'Position', [0.15 0.9 0.6 0.1]);
        tsvFileCtrl = uicontrol('Parent', panel, ...
            'Style', 'edit', ...
            'BackgroundColor', 'w', ...
            'HorizontalAlignment', 'Left', ...
            'String', '', ...
            'TooltipString', ['A tab-separated input file containing' ...
            ' HED tags.'], ...
            'Units','normalized',...
            'Callback', {@tagsCtrlCallback}, ...
            'Position', [0.15 0.75 0.6 0.1]);
        remapFileCtrl = uicontrol('Parent', panel, ...
            'Style', 'edit', ...
            'BackgroundColor', 'w', ...
            'HorizontalAlignment', 'Left', ...
            'String', '', ...
            'TooltipString', ['A tab-separated replacement file containing' ...
            ' tags that generated issues from a previous validation.' ...
            ' Any tags not in this file that generate issues will be' ...
            ' appended to first column.'], ...
            'Units','normalized',...
            'Callback', {@remapCtrlCallback}, ...
            'Position', [0.15 0.6 0.6 0.1]);
        outputDirectoryCtrl = uicontrol('Parent', panel, ...
            'Style', 'edit', ...
            'BackgroundColor', 'w', ...
            'HorizontalAlignment', 'Left', ...
            'String', pwd, ...
            'TooltipString', ['A directory where the validation output' ...
            ' is written to if the ''Write Output'' checkbox' ...
            ' is checked.'], ...
            'Units','normalized',...
            'Callback', {@outputCtrlCallback}, ...
            'Position', [0.15 0.45 0.6 0.1]);
        uicontrol('Parent', panel, ...
            'Style', 'edit', ...
            'BackgroundColor', 'w', ...
            'HorizontalAlignment', 'Left', ...
            'Tag', 'validateHedXmlEdit', ...
            'String', '2', ...
            'TooltipString', ['The tag columns in a tab-separated' ...
            ' input file. The columns can be specified as a single' ...
            ' number or a comma separated list of numbers (e.g. 2 or' ...
            ' 2,3,4)'], ...
            'Units','normalized',...
            'Callback', {@tsvTagColumnsCtrlCallback}, ...
            'Position', [0.15 0.3 0.6 0.1]);
    end % createEditBoxes

    function createLabels(panel)
        % Creates the labels in the panel
        uicontrol('parent', panel, ...
            'Style', 'Text', ...
            'Units', 'normalized', ...
            'String', 'XML HED schema', ...
            'HorizontalAlignment', 'Left', ...
            'Position', [0 0.9 0.12 0.08]);
        uicontrol('parent', panel, ...
            'Style', 'Text', ...
            'Units', 'normalized', ...
            'String', 'Tab-separated input file', ...
            'HorizontalAlignment', 'Left', ...
            'Position', [0 0.75 0.13 0.08]);
        uicontrol('parent', panel, ...
            'Style', 'Text', ...
            'Units', 'normalized', ...
            'String', 'Replacement file (optional)', ...
            'HorizontalAlignment', 'Left', ...
            'Position', [0 0.6 0.12 0.08]);
        uicontrol('parent', panel, ...
            'Style', 'Text', ...
            'Units', 'normalized', ...
            'String', 'Output directory', ...
            'HorizontalAlignment', 'Left', ...
            'Position', [0 0.45 0.12 0.1]);
        uicontrol('parent', panel, ...
            'Style', 'Text', ...
            'Units', 'normalized', ...
            'String', 'HED tag columns', ...
            'HorizontalAlignment', 'Left', ...
            'Position', [0 0.3 0.12 0.08]);
    end % createLabels

    function createPanel(tab)
        % Creates the 'Validate Tags' tab panel
        panel = uipanel('Parent', tab, ...
            'BorderType', 'none', ...
            'BackgroundColor', [.94 .94 .94], ...
            'FontSize', 12, ...
            'Position', [0 0 1 1]);
        createLabels(panel);
        createEditBoxes(panel);
        createCheckboxes();
        createButtons(panel);
    end % createPanel

    function tsvTagColumnsCtrlCallback(src, eventdata) %#ok<INUSD>
        % Callback for user directly editing the 'Columns' editbox
        tsvTagColumns = str2num(get(src, 'String')); %#ok<ST2NM>
    end % tsvTagColumnsCtrlCallback

    function hasHeaderCallback(src, eventdata) %#ok<INUSD>
        % Callback for user directly editing the 'Header' checkbox
        hasHeader = get(src, 'Max') == get(src, 'Value');
    end % hasHeaderCallback

    function errorLogCallback(src, eventdata) %#ok<INUSD>
        % Callback for only generate error log checkbox
        generateWarnings = get(src, 'Max') == get(src, 'Value');
    end % errorLogCallback

    function hedCtrlCallback(src, eventdata) %#ok<INUSD>
        % Callback for user directly editing the 'HED' editbox
        hedXML = get(src, 'String');
    end % hedCtrlCallback

    function remapCtrlCallback(src, eventdata) %#ok<INUSD>
        % Callback for user directly editing the 'HED' editbox
        remapFile = get(src, 'String');
    end % remapCtrlCallback

    function outputCtrlCallback(src, eventdata) %#ok<INUSD>
        % Callback for user directly editing the 'Output' editbox
        outDir = get(src, 'String');
    end % outputCtrlCallback

    function setOutputDirectory(dName)
        % Sets the 'Output' edit box based on the 'Tags' editbox
        outDir = dName;
        set(outputDirectoryCtrl, 'String', outDir);
    end % setOutputDirectory

    function tagsCtrlCallback(src, eventdata) %#ok<INUSD>
        % Callback for user directly editing the 'Tags' editbox
        tsvFile = get(src, 'String');
    end % tagsCtrlCallback

    function helpCallback(src, eventdata) %#ok<INUSD>
        % Callback for the 'Validate' button
        helpdlg(sprintf(['Validates the HED tags in a tab-separated' ...
            ' file using a HED schema. \n\n***Main Options***\n\nXML HED schema - The HED' ...
            ' schema file used to validate the HED tags in a tab-separated file.' ...
            ' This by default' ...
            ' will be the HED.xml file found in the hed directory.' ...
            ' If you want to be sure that you are using the latest' ...
            ' version click the ''Check For Latest HED'' tab and press' ...
            ' the ''Update'' button to check.' ... 
            ' \n\nTab-separated input file - A' ...
            ' tab-separated file containing HED tags in a single' ...
            ' column or multiple columns that will be validated.\n\nRemap file -' ...
            ' If a replacement file is provided then any HED tags not' ...
            ' already in this file that generate issues' ...
            ' will be appended to the end of it. Reusing a map file' ...
            ' comes in handy when you' ...
            ' have multiple tab-separated files that have the same' ...
            ' HED tags or you simply want to consolidate all of' ...
            ' the changes in one file instead of many.' ...
            '\n\nOutput directory - The directory where' ...
            ' the output files will be written to. There will be log' ...
            ' file containing any issues that were found while' ...
            ' validating the HED tags. If there were issues found then' ...
            ' a replacement file will be created in addition to the' ...
            ' log file. This file can be used to correct the' ...
            ' tab-separated input file. The default output' ...
            ' directory will be the current directory.\n\nHED tag ' ...
            ' columns - The HED tag columns are to' ...
            ' be specified with a single number or a comma separated' ...
            ' list of numbers (e.g. 1 or 1,2,3,4). The default will be' ...
            ' the second column.\n\n***Additional Options***' ...
            ' \n\nTab-separated input file has header - Check if the' ...
            ' the tab-separated' ...
            ' file has a header. If checked the first row will not be' ...
            ' validated, otherwise it will and this can generate' ...
            ' issues.''\n\nInclude warnings in ' ...
            ' log file - Check to include warnings as issues in the' ...
            ' log file in addition to errors. If unchecked only errors' ...
            ' are included in the log file.']), 'Validation Instructions');
    end % helpCallback

    function validateTSVTagsCallback(src, eventdata) %#ok<INUSD>
        % Callback for the 'Validate' button
        if isempty(hedXML)
            errordlg('HED file is empty');
        elseif isempty(tsvFile)
            errordlg('Tab-separated input file is empty');
        elseif isempty(outDir)
            errordlg('Output directory is empty');
        elseif isempty(tsvTagColumns)
            errordlg('HED tag columns are empty');
        else
            wb = waitbar(.5,'Please wait...');
            try
                validatetsv(tsvFile, tsvTagColumns, 'hedXML', ...
                    hedXML, 'outDir', outDir, ...
                    'hasHeader', hasHeader, 'writeOutput', true, ...
                    'generateWarnings', generateWarnings);
                msgbox('Complete!');
            catch ME
                errordlg(['Failed!' ME.message]);
            end
            close(wb);
        end
    end % validateTSVTagsCallback

end % validatetsv_input