% The following sections contain code examples for validating and replacing
% HED tags in tab-separated files. 

%% Set the example directory (PLEASE SET THIS)
exampleDir = 'C:\Users\jcockfie\Documents\HEDToolsExampleArchive\HEDToolsExampleArchive';

%% Validate the HED tags in a tab-separated file
issues = validatetsv([exampleDir filesep ... 
    'BCIT_GuardDuty_HED_tag_spec_v25.tsv'], ...
    [2,3,4,5,6]);

%% Find and replace the invalid HED tags with valid ones in a tab-separated file
replacetsv([exampleDir filesep ... 
    'BCIT_GuardDuty_HED_tag_spec_v25_replace.tsv'], ...
    [exampleDir filesep 'BCIT_GuardDuty_HED_tag_spec_v25.tsv'], ...
    [2,3,4,5,6]);