classdef ErrorConstants
    %ERRORCONSTANTS Summary of this class goes here
    %   Detailed explanation goes here
    
    properties(Constant = true)
        ErrorTypes = {'bracket', 'comma', 'duplicate', 'isNumeric', ...
            'row', 'column', 'required', 'requireChild', 'tilde', ...
            'unique', 'unitClass', 'valid'};
        ErrorMessages = {['\tERROR: Number of opening and closing' ...
            ' brackets are unequal. %s opening brackets. %s ' ...
            'closing brackets\n'], ...
            'comma': '\tERROR: Comma missing after - \"%s\"\n', ...
            'duplicate': '\tERROR: Duplicate tag - \"%s\"\n', ....
            'isNumeric': '\tERROR: Invalid numeric tag - \"%s\"\n', ...
            'row': 'Issues on row %s:\n', ...
            'column': 'Issues on row %s column %s:\n', ...
            ['required': '\tERROR: Tag with prefix \"%s\" is' ...
            'required\n'], ...
            ['requireChild':'\tERROR: Descendant tag required' ...
            ' - \"%s\"\n'], ...
            'tilde': '\tERROR: Too many tildes - group \"%s\"\n', ...
            ['unique': '\tERROR: Multiple unique tags with prefix' ...
            ' - \"%s\"\n'], ...
            ['unitClass': '\tERROR: Invalid unit - \"%s\" valid units' ...
            ' are "%s"\n'], ...
            'valid': '\tERROR: Invalid HED tag - \"%s\"\n'};
         PlaceHolderString = '%s';
    end % properties
    
end % ErrorConstants

