classdef ErrorConstants
    %ERRORCONSTANTS Summary of this class goes here
    %   Detailed explanation goes here
    
    properties(Constant = true)
        ErrorTypes = {'bracket', 'comma', 'duplicate', 'isNumeric', ...
            'row', 'column', 'required', 'requireChild', 'tilde', ...
            'unique', 'unitClass', 'valid'};
        ErrorMessages = {['Number of opening and closing' ...
            ' brackets are unequal. %s opening brackets. %s ' ...
            'closing brackets\n'], ...
            '\tERROR: Comma missing after - \"%s\"\n', ...
            '\tERROR: Duplicate tag - \"%s\"\n', ....
            '\tERROR: Invalid numeric tag - \"%s\"\n', ...
            'Issues on row %s:\n', ...
            'Issues on row %s column %s:\n', ...
            ['\tERROR: Tag with prefix \"%s\" is' ...
            'required\n'], ...
            ['\tERROR: Descendant tag required' ...
            ' - \"%s\"\n'], ...
            '\tERROR: Too many tildes - group \"%s\"\n', ...
            ['\tERROR: Multiple unique tags with prefix' ...
            ' - \"%s\"\n'], ...
            ['\tERROR: Invalid unit - \"%s\" valid units' ...
            ' are "%s"\n'], ...
            '\tERROR: Invalid HED tag - \"%s\"\n'};
         PlaceHolderString = '%s';
    end % properties
    
end % ErrorConstants

